import type { ActionRequest, ActivateInput, AdminPrincipal, AdminScope, APIClientInput, APIClientRecord, APIClientSecret, APIProblem, AssetRow, AuditRow, ConfigKind, DecisionInput, FinancialEnvelope, FinancialPageEnvelope, FinancialSettingsInventory, FinancialReconciliation, FinancialRefund, FinancialSource, FinancialSweep, HostedProviderPolicies, HostedProviderPolicyVersion, IntentRow, ManagementActionCategory, ManagementActionRequest, ManagementAuditEvent, ManagementPage, MatchingPolicyChange, MatchingPolicyInput, MerchantInvitation, MerchantMember, MerchantPage, MerchantProjectSettings, MerchantRole, MerchantRoleKey, MerchantSecurityAction, MigrationRun, OperatorCommand, OrdinaryMerchantRoleKey, Overview, Page, PauseInput, PaymentLink, PaymentLinkInput, PlatformChange, PlatformChangeInput, PlatformPage, PlatformSnapshot, ProviderBinding, ProviderChangeRequest, ProviderConfigurationInput, ProviderConfigurationVersion, ReconciliationRow, ResolutionRequest, RetentionArchiveBatch, RetentionDataClass, RetentionHold, RetentionHoldRelease, RetentionHoldScope, RetentionPolicy, RetentionPolicyChange, RetentionPolicyProposal, RetentionTombstone, RollbackInput, ScheduleInput, TransferRow, UnmatchedMutation, UnmatchedRow, WebhookDelivery, WebhookEndpoint, WebhookEndpointInput, WebhookEndpointSecret, WebhookEndpointUpdate, WebhookRow } from "./types";

type Fetch = typeof globalThis.fetch;
type RequestOptions = { method?:"GET"|"POST"|"PUT"|"PATCH";scope?:AdminScope;body?:unknown;signal?:AbortSignal;idempotencyKey?:string };

export class AdminAPIError extends Error {
  constructor(public readonly status:number,public readonly code:string,message:string){super(message);this.name="AdminAPIError"}
}

export function isAdminPreviewMode():boolean{return (import.meta as ImportMeta&{env?:Record<string,string|undefined>}).env?.VITE_ADMIN_PREVIEW_MODE === "true"}
function allowsInsecureLoopbackE2E():boolean{return (import.meta as ImportMeta&{env?:Record<string,string|undefined>}).env?.VITE_ADMIN_ALLOW_INSECURE_LOOPBACK_E2E === "true"}
export function isAllowedAdminOrigin(url:URL,allowInsecureLoopback=false):boolean{return url.protocol==="https:"||(allowInsecureLoopback&&url.protocol==="http:"&&["127.0.0.1","localhost","[::1]"].includes(url.hostname))}
export function adminCSRFCookieName(url:URL,allowInsecureLoopback=false):string{return allowInsecureLoopback&&url.protocol==="http:"&&isAllowedAdminOrigin(url,true)?"admin_csrf_e2e":"__Host-admin_csrf"}
export async function withExplicitPreviewFallback<T>(request:()=>Promise<T>,preview:()=>T):Promise<T>{try{return await request()}catch(error){if(isAdminPreviewMode())return preview();throw error}}

export class AdminClient {
  private readonly origin:string;
  constructor(private readonly fetcher:Fetch=(input,init)=>globalThis.fetch(input,init),baseURL?:string){
    const browserOrigin=typeof window!=="undefined"?window.location.origin:"https://admin.invalid";
    const parsed=new URL(baseURL??browserOrigin,browserOrigin);
    if(parsed.origin!==browserOrigin&&typeof window!=="undefined")throw new Error("Admin BFF must be same-origin");
    if(!isAllowedAdminOrigin(parsed,allowsInsecureLoopbackE2E()))throw new Error("Admin BFF requires HTTPS");
    this.origin=parsed.origin;
  }
  loginURL(returnPath="/"):string{if(!returnPath.startsWith("/")||returnPath.startsWith("//")||/[\\\r\n\0]/.test(returnPath))throw new Error("Unsafe return path");return `${this.origin}/admin/v1/auth/login?return=${encodeURIComponent(returnPath)}`}
  stepUpURL(returnPath="/"):string{if(!returnPath.startsWith("/")||returnPath.startsWith("//")||/[\\\r\n\0]/.test(returnPath))throw new Error("Unsafe return path");return `${this.origin}/admin/v1/auth/step-up?return=${encodeURIComponent(returnPath)}`}
  async beginInvitationLogin(token:string):Promise<string>{
    const response=await this.fetcher(`${this.origin}/admin/v1/auth/invitation`,{method:"POST",headers:new Headers({Accept:"application/json","Content-Type":"application/json"}),body:JSON.stringify({token}),credentials:"include",redirect:"error",cache:"no-store"});
    const value:unknown=await response.json().catch(()=>null);
    if(!response.ok){const problem=value as Partial<APIProblem>|null;throw new AdminAPIError(response.status,problem?.code??"http_error",problem?.detail??"Invitation login could not be started")}
    const authorizationURL=(value as {authorization_url?:unknown}|null)?.authorization_url;
    if(typeof authorizationURL!=="string")throw new AdminAPIError(502,"invalid_response","Invitation login response was invalid");
    const parsed=new URL(authorizationURL);
    if(parsed.protocol!=="https:"||parsed.username!==""||parsed.password!=="")throw new AdminAPIError(502,"invalid_response","Invitation login response was invalid");
    return parsed.toString();
  }
  me(signal?:AbortSignal){return this.request<AdminPrincipal>("/admin/v1/session/me",{signal})}
  logout(signal?:AbortSignal){return this.request<void>("/admin/v1/session/logout",{method:"POST",body:{},signal})}
  overview(scope:AdminScope,signal?:AbortSignal){return this.request<Overview>("/admin/v1/overview",{scope,signal})}
  intents(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.page<IntentRow>("/admin/v1/intents",scope,cursor,limit,signal)}
  transfers(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.page<TransferRow>("/admin/v1/transfers",scope,cursor,limit,signal)}
  unmatched(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.page<UnmatchedRow>("/admin/v1/unmatched",scope,cursor,limit,signal)}
  webhooks(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.page<WebhookRow>("/admin/v1/webhooks/endpoints",scope,cursor,limit,signal)}
  assets(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.page<AssetRow>("/admin/v1/assets",scope,cursor,limit,signal)}
  financialSettings(scope:AdminScope,signal?:AbortSignal){return this.request<FinancialSettingsInventory>("/admin/v1/financial-settings",{scope,signal})}
  reconciliation(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.page<ReconciliationRow>("/admin/v1/reconciliation",scope,cursor,limit,signal)}
  audit(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.page<AuditRow>("/admin/v1/audit",scope,cursor,limit,signal)}
  apiClients(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.managementPage<APIClientRecord>("/admin/v1/api-clients",scope,cursor,limit,signal)}
  createAPIClient(scope:AdminScope,input:APIClientInput,idempotencyKey:string){return this.request<APIClientSecret>("/admin/v1/api-clients",{method:"POST",scope,body:input,idempotencyKey})}
  rotateAPIClient(scope:AdminScope,id:string,version:number,overlapSeconds:number,idempotencyKey:string){return this.request<APIClientSecret>(`/admin/v1/api-clients/${pathID(id)}/rotate`,{method:"POST",scope,body:{version,overlap_seconds:overlapSeconds},idempotencyKey})}
  requestAPIClientRevoke(scope:AdminScope,id:string,version:number,reason:string,idempotencyKey:string){return this.request<ManagementActionRequest>(`/admin/v1/api-clients/${pathID(id)}/revoke-requests`,{method:"POST",scope,body:{version,reason},idempotencyKey})}
  paymentLinks(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.managementPage<PaymentLink>("/admin/v1/payment-links",scope,cursor,limit,signal)}
  createPaymentLink(scope:AdminScope,input:PaymentLinkInput,idempotencyKey:string){return this.request<PaymentLink>("/admin/v1/payment-links",{method:"POST",scope,body:input,idempotencyKey})}
  disablePaymentLink(scope:AdminScope,id:string,version:number,idempotencyKey:string){return this.request<PaymentLink>(`/admin/v1/payment-links/${pathID(id)}/disable`,{method:"POST",scope,body:{version},idempotencyKey})}
  webhookEndpoints(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.managementPage<WebhookEndpoint>("/admin/v1/webhooks/endpoints",scope,cursor,limit,signal)}
  createWebhookEndpoint(scope:AdminScope,input:WebhookEndpointInput,idempotencyKey:string){return this.request<WebhookEndpointSecret>("/admin/v1/webhooks/endpoints",{method:"POST",scope,body:input,idempotencyKey})}
  updateWebhookEndpoint(scope:AdminScope,id:string,input:WebhookEndpointUpdate,idempotencyKey:string){return this.request<WebhookEndpoint>(`/admin/v1/webhooks/endpoints/${pathID(id)}`,{method:"PATCH",scope,body:input,idempotencyKey})}
  verifyWebhookEndpoint(scope:AdminScope,id:string,version:number,idempotencyKey:string){return this.request<WebhookEndpoint>(`/admin/v1/webhooks/endpoints/${pathID(id)}/verify`,{method:"POST",scope,body:{version},idempotencyKey})}
  rotateWebhookEndpoint(scope:AdminScope,id:string,version:number,overlapSeconds:number,idempotencyKey:string){return this.request<WebhookEndpointSecret>(`/admin/v1/webhooks/endpoints/${pathID(id)}/rotate-secret`,{method:"POST",scope,body:{version,overlap_seconds:overlapSeconds},idempotencyKey})}
  requestWebhookDisable(scope:AdminScope,id:string,version:number,reason:string,idempotencyKey:string){return this.request<ManagementActionRequest>(`/admin/v1/webhooks/endpoints/${pathID(id)}/disable-requests`,{method:"POST",scope,body:{version,reason},idempotencyKey})}
  webhookDeliveries(scope:AdminScope,id:string,cursor="",limit=50,signal?:AbortSignal){return this.managementPage<WebhookDelivery>(`/admin/v1/webhooks/endpoints/${pathID(id)}/deliveries`,scope,cursor,limit,signal)}
  retryWebhookDelivery(scope:AdminScope,id:string,version:number,reason:string,idempotencyKey:string){return this.request<WebhookDelivery>(`/admin/v1/webhook-deliveries/${pathID(id)}/retry`,{method:"POST",scope,body:{version,reason},idempotencyKey})}
  managementAudit(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.managementPage<ManagementAuditEvent>("/admin/v1/management-audit",scope,cursor,limit,signal)}
  managementActions(scope:AdminScope,category:ManagementActionCategory,cursor="",limit=50,signal?:AbortSignal){return this.managementPage<ManagementActionRequest>(`/admin/v1/management-actions/${category}`,scope,cursor,limit,signal)}
  managementAction(scope:AdminScope,category:ManagementActionCategory,id:string,signal?:AbortSignal){return this.request<ManagementActionRequest>(`/admin/v1/management-actions/${category}/${pathID(id)}`,{scope,signal})}
  decideManagementAction(scope:AdminScope,category:ManagementActionCategory,id:string,decision:"approve"|"reject",reason:string,idempotencyKey:string){return this.request<ManagementActionRequest>(`/admin/v1/management-actions/${category}/${pathID(id)}/${decision}`,{method:"POST",scope,body:{reason},idempotencyKey})}
  matchingPolicies(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.managementPage<MatchingPolicyChange>("/admin/v1/matching-policies",scope,cursor,limit,signal)}
  matchingPolicy(scope:AdminScope,id:string,signal?:AbortSignal){return this.request<MatchingPolicyChange>(`/admin/v1/matching-policies/${pathID(id)}`,{scope,signal})}
  createMatchingPolicy(scope:AdminScope,input:MatchingPolicyInput,idempotencyKey:string){return this.request<MatchingPolicyChange>("/admin/v1/matching-policies",{method:"POST",scope,body:input,idempotencyKey})}
  mutateMatchingPolicy(scope:AdminScope,id:string,action:"request-approval"|"approve",version:number,reason:string,idempotencyKey:string){return this.request<MatchingPolicyChange>(`/admin/v1/matching-policies/${pathID(id)}/${action}`,{method:"POST",scope,body:{version,reason},idempotencyKey})}
  activateMatchingPolicy(scope:AdminScope,id:string,version:number,reason:string,effectiveAt:string,idempotencyKey:string){return this.request<MatchingPolicyChange>(`/admin/v1/matching-policies/${pathID(id)}/activate`,{method:"POST",scope,body:{version,reason,effective_at:effectiveAt},idempotencyKey})}
  platformChanges(scope:AdminScope,filters:{kind?:ConfigKind;status?:string;cursor?:string;limit?:number}={},signal?:AbortSignal){const query=new URLSearchParams({limit:String(filters.limit??50)});if(filters.kind)query.set("kind",filters.kind);if(filters.status)query.set("status",filters.status);if(filters.cursor)query.set("cursor",filters.cursor);return this.request<PlatformPage<PlatformChange>>(`/admin/v1/platform/changes?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  createPlatformChange(scope:AdminScope,input:PlatformChangeInput,idempotencyKey:string){return this.request<PlatformChange>("/admin/v1/platform/changes",{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  decidePlatformChange(scope:AdminScope,id:string,action:"request-approval"|"approve"|"reject",input:DecisionInput,idempotencyKey:string){return this.request<PlatformChange>(`/admin/v1/platform/changes/${pathID(id)}/${action}`,{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  schedulePlatformChange(scope:AdminScope,id:string,input:ScheduleInput,idempotencyKey:string){return this.request<PlatformChange>(`/admin/v1/platform/changes/${pathID(id)}/schedule`,{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  activatePlatformChange(scope:AdminScope,id:string,input:ActivateInput,idempotencyKey:string){return this.request<PlatformSnapshot>(`/admin/v1/platform/changes/${pathID(id)}/activate`,{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  platformSnapshots(scope:AdminScope,filters:{kind?:ConfigKind;logicalKey?:string;cursor?:string;limit?:number}={},signal?:AbortSignal){const query=new URLSearchParams({limit:String(filters.limit??50)});if(filters.kind)query.set("kind",filters.kind);if(filters.logicalKey)query.set("logical_key",filters.logicalKey);if(filters.cursor)query.set("cursor",filters.cursor);return this.request<PlatformPage<PlatformSnapshot>>(`/admin/v1/platform/snapshots?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  rollbackPlatformSnapshot(scope:AdminScope,input:RollbackInput,idempotencyKey:string){return this.request<PlatformChange>("/admin/v1/platform/rollbacks",{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  emergencyPlatformPause(scope:AdminScope,input:PauseInput,idempotencyKey:string){return this.request<void>("/admin/v1/platform/emergency-pauses",{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  providerBindings(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<PlatformPage<ProviderBinding>>(`/admin/v1/providers?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  providerChanges(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<PlatformPage<ProviderChangeRequest>>(`/admin/v1/provider-change-requests?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  providerPolicies(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<PlatformPage<HostedProviderPolicyVersion>>(`/admin/v1/provider-policy-requests?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  requestProviderStatus(scope:AdminScope,id:string,status:"active"|"paused",expectedVersion:number,reason:string,idempotencyKey:string){const action=status==="paused"?"pause-requests":"unpause-requests";return this.request<ProviderChangeRequest>(`/admin/v1/providers/${pathID(id)}/${action}`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_binding_version:expectedVersion,reason},idempotencyKey})}
  decideProviderChange(scope:AdminScope,id:string,approve:boolean,expectedVersion:number,reason:string,idempotencyKey:string){return this.request<ProviderChangeRequest>(`/admin/v1/provider-change-requests/${pathID(id)}/${approve?"approve":"reject"}`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_request_version:expectedVersion,reason},idempotencyKey})}
  requestProviderPolicy(scope:AdminScope,id:string,expectedVersion:number,policies:HostedProviderPolicies,bootstrapProbeReference:string,reason:string,idempotencyKey:string){return this.request<HostedProviderPolicyVersion>(`/admin/v1/providers/${pathID(id)}/policy-requests`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_binding_version:expectedVersion,policies,bootstrap_probe_reference:bootstrapProbeReference,reason},idempotencyKey})}
  decideProviderPolicy(scope:AdminScope,id:string,approve:boolean,expectedVersion:number,reason:string,idempotencyKey:string){return this.request<HostedProviderPolicyVersion>(`/admin/v1/provider-policy-requests/${pathID(id)}/${approve?"approve":"reject"}`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_request_version:expectedVersion,reason},idempotencyKey})}
  providerConfigurationVersions(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<PlatformPage<ProviderConfigurationVersion>>(`/admin/v1/provider-config-versions?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  requestProviderConfiguration(scope:AdminScope,providerID:string,input:ProviderConfigurationInput,idempotencyKey:string){return this.request<ProviderConfigurationVersion>(`/admin/v1/provider-configurations/${providerConfigurationID(providerID)}/requests`,{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  decideProviderConfiguration(scope:AdminScope,id:string,approve:boolean,expectedVersion:number,reason:string,idempotencyKey:string){return this.request<ProviderConfigurationVersion>(`/admin/v1/provider-config-requests/${pathID(id)}/${approve?"approve":"reject"}`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_row_version:expectedVersion,reason},idempotencyKey})}
  retentionPolicies(scope:AdminScope,signal?:AbortSignal){return this.request<{items:RetentionPolicy[]}>("/admin/v1/retention/policies",{scope:{tenantId:scope.tenantId},signal})}
  retentionPolicyChanges(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.retentionPage<RetentionPolicyChange>("/admin/v1/retention/policy-requests",scope,cursor,limit,signal)}
  requestRetentionPolicy(scope:AdminScope,dataClass:RetentionDataClass,expectedPolicyVersion:number,expectedHeadFence:number,proposal:RetentionPolicyProposal,scheduledFor:string,reason:string,idempotencyKey:string){return this.request<RetentionPolicyChange>("/admin/v1/retention/policy-requests",{method:"POST",scope:{tenantId:scope.tenantId},body:{data_class:dataClass,expected_policy_version:expectedPolicyVersion,expected_head_fence:expectedHeadFence,...proposal,scheduled_for:scheduledFor,reason},idempotencyKey})}
  decideRetentionPolicy(scope:AdminScope,id:string,approve:boolean,expectedRowVersion:number,reason:string,idempotencyKey:string){return this.request<RetentionPolicyChange>(`/admin/v1/retention/policy-requests/${pathID(id)}/${approve?"approve":"reject"}`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_row_version:expectedRowVersion,reason},idempotencyKey})}
  retentionHolds(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.retentionPage<RetentionHold>("/admin/v1/retention/holds",scope,cursor,limit,signal)}
  createRetentionHold(scope:AdminScope,input:{data_class:RetentionDataClass;scope_type:RetentionHoldScope;merchant_id?:string;source_table?:string;source_record_id?:string;case_reference:string;reason:string;expires_at?:string},idempotencyKey:string){return this.request<RetentionHold>("/admin/v1/retention/holds",{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  requestRetentionHoldRelease(scope:AdminScope,id:string,expectedHoldVersion:number,reason:string,idempotencyKey:string){return this.request<RetentionHoldRelease>(`/admin/v1/retention/holds/${pathID(id)}/release-requests`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_hold_version:expectedHoldVersion,reason},idempotencyKey})}
  retentionHoldReleases(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.retentionPage<RetentionHoldRelease>("/admin/v1/retention/hold-release-requests",scope,cursor,limit,signal)}
  decideRetentionHoldRelease(scope:AdminScope,id:string,approve:boolean,expectedRowVersion:number,reason:string,idempotencyKey:string){return this.request<RetentionHoldRelease>(`/admin/v1/retention/hold-release-requests/${pathID(id)}/${approve?"approve":"reject"}`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_row_version:expectedRowVersion,reason},idempotencyKey})}
  retentionArchiveBatches(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.retentionPage<RetentionArchiveBatch>("/admin/v1/retention/archive-batches",scope,cursor,limit,signal)}
  retentionTombstones(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.retentionPage<RetentionTombstone>("/admin/v1/retention/tombstones",scope,cursor,limit,signal)}
  migrationRuns(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<PlatformPage<MigrationRun>>(`/admin/v1/platform/migrations?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  teamRoles(scope:AdminScope,signal?:AbortSignal){return this.request<MerchantPage<MerchantRole>>("/admin/v1/team/roles",{scope,signal})}
  teamMembers(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.merchantPage<MerchantMember>("/admin/v1/team/members",scope,cursor,limit,signal)}
  teamInvitations(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.merchantPage<MerchantInvitation>("/admin/v1/team/invitations",scope,cursor,limit,signal)}
  teamSecurityActions(scope:AdminScope,cursor="",limit=50,signal?:AbortSignal){return this.merchantPage<MerchantSecurityAction>("/admin/v1/team/security-actions",scope,cursor,limit,signal)}
  createTeamInvitation(scope:AdminScope,input:{email:string;role_keys:OrdinaryMerchantRoleKey[];delivery_mode:"copy_once"|"email";ttl_seconds:number;reason:string},idempotencyKey:string){return this.request<MerchantInvitation>("/admin/v1/team/invitations",{method:"POST",scope,body:input,idempotencyKey})}
  revokeTeamInvitation(scope:AdminScope,id:string,version:number,reason:string,idempotencyKey:string){return this.request<MerchantInvitation>(`/admin/v1/team/invitations/${pathID(id)}/revoke`,{method:"POST",scope,body:{version,reason},idempotencyKey})}
  changeMemberRoles(scope:AdminScope,id:string,version:number,roleKeys:MerchantRoleKey[],reason:string,idempotencyKey:string){return this.request<MerchantMember>(`/admin/v1/team/members/${pathID(id)}/roles`,{method:"POST",scope,body:{version,role_keys:roleKeys,reason},idempotencyKey})}
  mutateMember(scope:AdminScope,id:string,action:"disable"|"remove",version:number,reason:string,idempotencyKey:string){return this.request<MerchantMember>(`/admin/v1/team/members/${pathID(id)}/${action}`,{method:"POST",scope,body:{version,reason},idempotencyKey})}
  requestTeamSecurityAction(scope:AdminScope,input:{operation:MerchantSecurityAction["operation"];target_member_id:string;target_version:number;desired_role_keys:MerchantRoleKey[];reason:string},idempotencyKey:string){return this.request<MerchantSecurityAction>("/admin/v1/team/security-actions",{method:"POST",scope,body:input,idempotencyKey})}
  decideTeamSecurityAction(scope:AdminScope,id:string,decision:"approve"|"reject",version:number,reason:string,idempotencyKey:string){return this.request<MerchantSecurityAction>(`/admin/v1/team/security-actions/${pathID(id)}/${decision}`,{method:"POST",scope,body:{version,reason},idempotencyKey})}
  acceptTeamInvitation(token:string,idempotencyKey:string){return this.request<MerchantMember>("/admin/v1/team/invitations/accept",{method:"POST",body:{token},idempotencyKey})}
  projectSettings(scope:AdminScope,signal?:AbortSignal){return this.request<MerchantProjectSettings>("/admin/v1/project-settings",{scope,signal})}
  updateProjectSettings(scope:AdminScope,input:Omit<MerchantProjectSettings,"updated_at">&{reason:string},idempotencyKey:string){return this.request<MerchantProjectSettings>("/admin/v1/project-settings",{method:"PUT",scope,body:input,idempotencyKey})}
  financialSweeps(scope:AdminScope,after="",limit=50,signal?:AbortSignal){return this.financialPage<FinancialSweep>("/admin/v1/financial/sweeps",scope,after,limit,signal)}
  financialSweep(scope:AdminScope,id:string,signal?:AbortSignal){return this.request<FinancialEnvelope<FinancialSweep>>(`/admin/v1/financial/sweeps/${pathID(id)}`,{scope:{tenantId:scope.tenantId},signal})}
  createFinancialSweep(scope:AdminScope,input:{asset_id:string;destination:{chain:string;value:string};sources:FinancialSource[];fee_quote:string},idempotencyKey:string){return this.request<FinancialEnvelope<FinancialSweep>>("/admin/v1/financial/sweeps",{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  decideFinancialSweep(scope:AdminScope,id:string,action:"approve"|"cancel",expectedVersion:number,reason:string,idempotencyKey:string){return this.request<FinancialEnvelope<FinancialSweep>>(`/admin/v1/financial/sweeps/${pathID(id)}/${action}`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_version:expectedVersion,reason},idempotencyKey})}
  financialRefunds(scope:AdminScope,after="",limit=50,signal?:AbortSignal){return this.financialPage<FinancialRefund>("/admin/v1/financial/refunds",scope,after,limit,signal)}
  financialRefund(scope:AdminScope,id:string,signal?:AbortSignal){return this.request<FinancialEnvelope<FinancialRefund>>(`/admin/v1/financial/refunds/${pathID(id)}`,{scope:{tenantId:scope.tenantId},signal})}
  createFinancialRefund(scope:AdminScope,input:{settlement_id:string;destination_verification_id:string;refund_amount:string;network_fee:string},idempotencyKey:string){return this.request<FinancialEnvelope<FinancialRefund>>("/admin/v1/financial/refunds",{method:"POST",scope:{tenantId:scope.tenantId},body:input,idempotencyKey})}
  decideFinancialRefund(scope:AdminScope,id:string,action:"approve"|"cancel",expectedVersion:number,reason:string,idempotencyKey:string){return this.request<FinancialEnvelope<FinancialRefund>>(`/admin/v1/financial/refunds/${pathID(id)}/${action}`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_version:expectedVersion,reason},idempotencyKey})}
  financialReconciliations(scope:AdminScope,after="",limit=50,signal?:AbortSignal){return this.financialPage<FinancialReconciliation>("/admin/v1/financial/reconciliation-runs",scope,after,limit,signal)}
  financialReconciliation(scope:AdminScope,id:string,signal?:AbortSignal){return this.request<FinancialEnvelope<FinancialReconciliation>>(`/admin/v1/financial/reconciliation-runs/${pathID(id)}`,{scope:{tenantId:scope.tenantId},signal})}
  createFinancialReconciliation(scope:AdminScope,assetIds:string[],idempotencyKey:string){return this.request<FinancialEnvelope<FinancialReconciliation>>("/admin/v1/financial/reconciliation-runs",{method:"POST",scope:{tenantId:scope.tenantId},body:{asset_ids:assetIds},idempotencyKey})}
  executeFinancialReconciliation(scope:AdminScope,id:string,expectedVersion:number,cutoffAt:string,reason:string,idempotencyKey:string){return this.request<FinancialEnvelope<FinancialReconciliation>>(`/admin/v1/financial/reconciliation-runs/${pathID(id)}/execute`,{method:"POST",scope:{tenantId:scope.tenantId},body:{expected_version:expectedVersion,cutoff_at:cutoffAt,reason},idempotencyKey})}
  claimUnmatched(scope:AdminScope,id:string,input:OperatorCommand){return this.request<UnmatchedRow>(`/admin/v1/unmatched/${pathID(id)}/claim`,{method:"POST",scope,body:input})}
  releaseUnmatched(scope:AdminScope,id:string,input:OperatorCommand){return this.request<UnmatchedRow>(`/admin/v1/unmatched/${pathID(id)}/release`,{method:"POST",scope,body:input})}
  hideUnmatched(scope:AdminScope,id:string,input:OperatorCommand){return this.request<UnmatchedMutation>(`/admin/v1/unmatched/${pathID(id)}/hide`,{method:"POST",scope,body:input})}
  requestResolution(scope:AdminScope,id:string,input:ResolutionRequest){return this.request<ActionRequest>(`/admin/v1/unmatched/${pathID(id)}/resolution-requests`,{method:"POST",scope,body:input})}
  action(scope:AdminScope,id:string){return this.request<ActionRequest>(`/admin/v1/action-requests/${pathID(id)}`,{scope})}
  approveAction(scope:AdminScope,id:string,reason:string){return this.request<ActionRequest>(`/admin/v1/action-requests/${pathID(id)}/approve`,{method:"POST",scope,body:{reason}})}
  rejectAction(scope:AdminScope,id:string,reason:string){return this.request<ActionRequest>(`/admin/v1/action-requests/${pathID(id)}/reject`,{method:"POST",scope,body:{reason}})}
  replayDelivery(scope:AdminScope,id:string,reason:string,idempotencyKey:string){return this.request<void>(`/admin/v1/webhook-deliveries/${pathID(id)}/replay`,{method:"POST",scope,body:{reason,idempotency_key:idempotencyKey}})}
  private page<T>(path:string,scope:AdminScope,cursor:string,limit:number,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<Page<T>>(`${path}?${query}`,{scope,signal})}
  private managementPage<T>(path:string,scope:AdminScope,cursor:string,limit:number,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<ManagementPage<T>>(`${path}?${query}`,{scope,signal})}
  private merchantPage<T>(path:string,scope:AdminScope,cursor:string,limit:number,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<MerchantPage<T>>(`${path}?${query}`,{scope,signal})}
  private financialPage<T>(path:string,scope:AdminScope,after:string,limit:number,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(after)query.set("after",after);return this.request<FinancialPageEnvelope<T>>(`${path}?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  private retentionPage<T>(path:string,scope:AdminScope,cursor:string,limit:number,signal?:AbortSignal){const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set("cursor",cursor);return this.request<PlatformPage<T>>(`${path}?${query}`,{scope:{tenantId:scope.tenantId},signal})}
  private async request<T>(path:string,options:RequestOptions={}):Promise<T>{
    const headers=new Headers({Accept:"application/json"});
    if(options.scope){headers.set("X-Admin-Tenant-ID",options.scope.tenantId);if(options.scope.merchantId)headers.set("X-Admin-Merchant-ID",options.scope.merchantId)}
    let body:string|undefined;
    if(options.method==="POST"||options.method==="PUT"||options.method==="PATCH"){headers.set("Content-Type","application/json");headers.set("X-CSRF-Token",readUniqueCookie(adminCSRFCookieName(new URL(this.origin),allowsInsecureLoopbackE2E())));if(options.idempotencyKey)headers.set("Idempotency-Key",options.idempotencyKey);body=JSON.stringify(options.body??{})}
    const response=await this.fetcher(`${this.origin}${path}`,{method:options.method??"GET",headers,body,credentials:"include",redirect:"error",cache:"no-store",signal:options.signal});
    if(response.status===204)return undefined as T;
    const value:unknown=await response.json().catch(()=>null);
    if(!response.ok){const problem=value as (Partial<APIProblem>&{error?:{code?:string;message?:string}})|null;throw new AdminAPIError(response.status,problem?.error?.code??problem?.code??"http_error",problem?.error?.message??problem?.detail??"Admin request failed")}
    return normalizeListEnvelope(value) as T;
  }
}

function normalizeListEnvelope(value:unknown):unknown{
  if(value===null||typeof value!=="object"||Array.isArray(value))return value;
  const record=value as Record<string,unknown>;
  const keys=Object.keys(record);
  const pageOnly=keys.every((key)=>key==="items"||key==="data"||key==="next_cursor");
  if(!pageOnly)return value;
  if((Object.prototype.hasOwnProperty.call(record,"items")||Object.prototype.hasOwnProperty.call(record,"next_cursor"))&&!Array.isArray(record.items))return{...record,items:[]};
  if((Object.prototype.hasOwnProperty.call(record,"data")||Object.prototype.hasOwnProperty.call(record,"next_cursor"))&&!Array.isArray(record.data))return{...record,data:[]};
  return value;
}

function readUniqueCookie(name:string):string{if(typeof document==="undefined")throw new AdminAPIError(403,"csrf_unavailable","CSRF cookie is unavailable");const values=document.cookie.split(";").map((part)=>part.trim()).filter((part)=>part.startsWith(`${name}=`)).map((part)=>decodeURIComponent(part.slice(name.length+1)));const value=values[0];if(values.length!==1||value===undefined||value.length<43)throw new AdminAPIError(403,"csrf_unavailable","CSRF cookie is unavailable");return value}
function pathID(value:string):string{if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(value))throw new Error("Invalid resource ID");return encodeURIComponent(value)}
function providerConfigurationID(value:string):string{if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value))throw new Error("Invalid provider ID");return encodeURIComponent(value)}
