import { beforeEach, describe, expect, it, vi } from "vitest";
import { adminCSRFCookieName, AdminAPIError, AdminClient, isAllowedAdminOrigin } from "./client";

describe("AdminClient",()=>{
  beforeEach(()=>{Object.defineProperty(document,"cookie",{configurable:true,writable:true,value:"__Host-admin_csrf="+"c".repeat(43)})});
  const build=(fetcher:typeof fetch)=>{const current=window;vi.stubGlobal("window",undefined);const client=new AdminClient(fetcher,"https://admin.invalid");vi.stubGlobal("window",current);return client};
  it("limits the test-only HTTP exception and cookie to exact loopback hosts",()=>{expect(isAllowedAdminOrigin(new URL("https://admin.example"))).toBe(true);expect(isAllowedAdminOrigin(new URL("http://127.0.0.1:4176"),true)).toBe(true);expect(isAllowedAdminOrigin(new URL("http://localhost:4176"),true)).toBe(true);expect(isAllowedAdminOrigin(new URL("http://merchant.example"),true)).toBe(false);expect(isAllowedAdminOrigin(new URL("http://127.0.0.1.evil.example"),true)).toBe(false);expect(isAllowedAdminOrigin(new URL("http://127.0.0.1:4176"),false)).toBe(false);expect(adminCSRFCookieName(new URL("http://127.0.0.1:4176"),true)).toBe("admin_csrf_e2e");expect(adminCSRFCookieName(new URL("https://127.0.0.1:4176"),true)).toBe("__Host-admin_csrf");expect(adminCSRFCookieName(new URL("http://merchant.example"),true)).toBe("__Host-admin_csrf")});
  it("keeps the browser receiver when using the default fetch implementation",async()=>{const currentWindow=window;const originalFetch=globalThis.fetch;const requiresReceiver=vi.fn(function(this:unknown){if(this!==globalThis)throw new TypeError("Illegal invocation");return Promise.resolve(new Response(JSON.stringify({user_id:"10000000-0000-4000-8000-000000000001"}),{status:200,headers:{"Content-Type":"application/json"}}))});vi.stubGlobal("fetch",requiresReceiver);vi.stubGlobal("window",undefined);const client=new AdminClient(undefined,"https://admin.invalid");vi.stubGlobal("window",currentWindow);await client.me();expect(requiresReceiver).toHaveBeenCalledOnce();vi.stubGlobal("fetch",originalFetch)});
  it("always sends same-origin credentials and scoped headers",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({items:[]}),{status:200,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);await client.intents({tenantId:"tenant",merchantId:"merchant"});expect(fetcher).toHaveBeenCalledWith(expect.stringContaining("/admin/v1/intents"),expect.objectContaining({credentials:"include",cache:"no-store",redirect:"error"}));const calls=fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>;const options=calls[0]?.[1];expect(options).toBeDefined();expect((options?.headers as Headers).get("X-Admin-Tenant-ID")).toBe("tenant");expect((options?.headers as Headers).get("X-Admin-Merchant-ID")).toBe("merchant")});
  it("normalizes legacy null list envelopes before pages render",async()=>{const managementFetcher=vi.fn(async()=>new Response(JSON.stringify({data:null}),{status:200,headers:{"Content-Type":"application/json"}}));const managementClient=build(managementFetcher as typeof fetch);await expect(managementClient.webhookEndpoints({tenantId:"tenant",merchantId:"merchant"})).resolves.toEqual({data:[]});const platformFetcher=vi.fn(async()=>new Response(JSON.stringify({items:null}),{status:200,headers:{"Content-Type":"application/json"}}));const platformClient=build(platformFetcher as typeof fetch);await expect(platformClient.platformChanges({tenantId:"tenant"})).resolves.toEqual({items:[]})});
  it("adds CSRF to mutations without merchant HMAC material",async()=>{const fetcher=vi.fn(async()=>new Response(null,{status:204}));const client=build(fetcher as typeof fetch);await client.logout();const calls=fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>;const options=calls[0]?.[1];expect(options).toBeDefined();const headers=options?.headers as Headers;expect(headers.get("X-CSRF-Token")).toHaveLength(43);expect(headers.get("Authorization")).toBeNull();expect(JSON.stringify(options)).not.toContain("hmac")});
  it("refreshes a stale action token without sending the stale token",async()=>{document.cookie="";const fetcher=vi.fn(async()=>new Response(null,{status:204}));const client=build(fetcher as typeof fetch);await client.refreshCSRF();const[url,options]=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]??[];expect(String(url)).toBe("https://admin.invalid/admin/v1/session/csrf");expect(options?.method).toBe("POST");expect(options?.credentials).toBe("include");expect((options?.headers as Headers).get("X-CSRF-Token")).toBeNull()});
  it("fails closed when the CSRF cookie is missing",async()=>{document.cookie="";const client=build(vi.fn() as unknown as typeof fetch);await expect(client.logout()).rejects.toMatchObject({code:"csrf_unavailable"} satisfies Partial<AdminAPIError>)});
  it("surfaces not-implemented endpoints instead of fixture data",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({code:"not_implemented",detail:"No preview"}),{status:501,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);await expect(client.paymentLinks({tenantId:"tenant"})).rejects.toMatchObject({status:501,code:"not_implemented"})});
  it("rejects open redirect return paths",()=>{const client=build(vi.fn() as unknown as typeof fetch);for(const path of ["//evil.example","/ok\\evil","/ok\nnext"]){expect(()=>client.loginURL(path)).toThrow("Unsafe return path");expect(()=>client.stepUpURL(path)).toThrow("Unsafe return path")}});
  it("sends management mutations through the scoped BFF with header idempotency",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({id:"10000000-0000-4000-8000-000000000001",public_url:"https://checkout.example/pay?token=pl_safe",name:"Invoice",amount_minor:"3813",currency:"USD",currency_scale:2,description:"Order",allowed_routes:[{provider:"on_chain",chain_id:"tron",asset_id:"usdt-trc20"}],metadata:{},success_url:"https://merchant.example/success",cancel_url:"https://merchant.example/cancel",max_uses:1,use_count:0,settled_count:0,settled_minor:"0",status:"active",created_at:"2026-08-11T00:00:00Z",updated_at:"2026-08-11T00:00:00Z",version:1}),{status:201,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);await client.createPaymentLink({tenantId:"tenant",merchantId:"merchant"},{name:"Invoice",amount_minor:"3813",currency:"USD",currency_scale:2,description:"Order",allowed_routes:[{provider:"on_chain",chain_id:"tron",asset_id:"usdt-trc20"}],metadata:{},success_url:"https://merchant.example/success",cancel_url:"https://merchant.example/cancel",max_uses:1},"create-link-0001");const calls=fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>;const [url,options]=calls[0]??[];expect(String(url)).toBe("https://admin.invalid/admin/v1/payment-links");expect(options?.method).toBe("POST");const headers=options?.headers as Headers;expect(headers.get("Idempotency-Key")).toBe("create-link-0001");expect(headers.get("X-CSRF-Token")).toHaveLength(43);expect(headers.get("Merchant-Signature")).toBeNull();expect(JSON.parse(String(options?.body))).toMatchObject({amount_minor:"3813",allowed_routes:[{provider:"on_chain",chain_id:"tron",asset_id:"usdt-trc20"}]})});
  it("uses PATCH plus optimistic version for endpoint updates",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({id:"10000000-0000-4000-8000-000000000001",url:"https://merchant.example/hook",event_types:["payment.settled"],timeout_ms:5000,max_concurrency:4,status:"active",signing_key_id:"whk_live",created_at:"2026-08-11T00:00:00Z",updated_at:"2026-08-11T00:00:00Z",version:8}),{status:200,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);await client.updateWebhookEndpoint({tenantId:"tenant",merchantId:"merchant"},"10000000-0000-4000-8000-000000000001",{url:"https://merchant.example/hook",event_types:["payment.settled"],timeout_ms:5000,max_concurrency:4,version:7},"update-hook-001");const options=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]?.[1];expect(options?.method).toBe("PATCH");expect((options?.headers as Headers).get("Idempotency-Key")).toBe("update-hook-001");expect(JSON.parse(String(options?.body))).toMatchObject({version:7})});
  it("creates revocation requests without calling the internal execution route",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({id:"20000000-0000-4000-8000-000000000001",operation:"api_client.revoke",resource_type:"api_client",resource_id:"10000000-0000-4000-8000-000000000001",resource_version:2,request_reason:"Approved security change",requested_by:"30000000-0000-4000-8000-000000000001",status:"pending_approval",created_at:"2026-08-11T00:00:00Z",expires_at:"2026-08-11T00:10:00Z",updated_at:"2026-08-11T00:00:00Z",version:1}),{status:202,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);await client.requestAPIClientRevoke({tenantId:"tenant",merchantId:"merchant"},"10000000-0000-4000-8000-000000000001",2,"Approved security change","revoke-client-1");const [url,options]=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]??[];expect(String(url)).toMatch(/\/admin\/v1\/api-clients\/10000000-0000-4000-8000-000000000001\/revoke-requests$/);expect(String(url)).not.toMatch(/\/revoke$/);expect((options?.headers as Headers).get("Idempotency-Key")).toBe("revoke-client-1");expect(JSON.parse(String(options?.body))).toEqual({version:2,reason:"Approved security change"})});
  it("binds independent decisions to category, request and idempotency",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({id:"20000000-0000-4000-8000-000000000001",operation:"webhook.disable",resource_type:"webhook_endpoint",resource_id:"10000000-0000-4000-8000-000000000001",resource_version:3,request_reason:"Endpoint compromised",requested_by:"30000000-0000-4000-8000-000000000001",approved_by:"30000000-0000-4000-8000-000000000002",approval_reason:"Evidence verified",status:"completed",created_at:"2026-08-11T00:00:00Z",expires_at:"2026-08-11T00:10:00Z",updated_at:"2026-08-11T00:01:00Z",version:2}),{status:200,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);await client.decideManagementAction({tenantId:"tenant",merchantId:"merchant"},"webhook-disable","20000000-0000-4000-8000-000000000001","approve","Evidence verified","approve-action-1");const [url,options]=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]??[];expect(String(url)).toMatch(/\/admin\/v1\/management-actions\/webhook-disable\/20000000-0000-4000-8000-000000000001\/approve$/);expect(JSON.parse(String(options?.body))).toEqual({reason:"Evidence verified"});expect((options?.headers as Headers).get("Idempotency-Key")).toBe("approve-action-1")});
  it("implements the matching lifecycle without inventing a reject request",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({id:"10000000-0000-4000-8000-000000000001",proposed_version:4,accumulate_partials:true,underpayment_tolerance_bps:50,overpayment_mode:"manual_review",accept_late_within_grace:true,require_same_sender:true,gasfree_enabled:false,gasfree_fee_collectors:[],status:"pending_approval",created_by:"20000000-0000-4000-8000-000000000001",created_at:"2026-08-11T00:00:00Z",updated_at:"2026-08-11T00:00:00Z",version:2}),{status:200,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);await client.mutateMatchingPolicy({tenantId:"tenant",merchantId:"merchant"},"10000000-0000-4000-8000-000000000001","request-approval",1,"Policy evidence verified","matching-request-1");const [url,options]=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]??[];expect(String(url)).toMatch(/\/admin\/v1\/matching-policies\/10000000-0000-4000-8000-000000000001\/request-approval$/);expect(String(url)).not.toContain("/reject");expect(JSON.parse(String(options?.body))).toEqual({version:1,reason:"Policy evidence verified"})});
  it("keeps invitation acceptance unscoped and token-only",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({id:"10000000-0000-4000-8000-000000000001"}),{status:200,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);const token="a".repeat(43);await client.acceptTeamInvitation(token,"accept-invite-1");const[url,options]=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]??[];const headers=options?.headers as Headers;expect(String(url)).toBe("https://admin.invalid/admin/v1/team/invitations/accept");expect(headers.get("X-Admin-Tenant-ID")).toBeNull();expect(headers.get("X-Admin-Merchant-ID")).toBeNull();expect(headers.get("Idempotency-Key")).toBe("accept-invite-1");expect(JSON.parse(String(options?.body))).toEqual({token})});
  it("starts invitation OIDC through a same-origin token-only POST without CSRF or scope",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({authorization_url:"https://id.example/authorize?state=opaque"}),{status:200,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);const token="a".repeat(43);await expect(client.beginInvitationLogin(token)).resolves.toContain("https://id.example/authorize");const[url,options]=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]??[];const headers=options?.headers as Headers;expect(String(url)).toBe("https://admin.invalid/admin/v1/auth/invitation");expect(options?.credentials).toBe("include");expect(options?.redirect).toBe("error");expect(headers.get("X-CSRF-Token")).toBeNull();expect(headers.get("X-Admin-Tenant-ID")).toBeNull();expect(JSON.parse(String(options?.body))).toEqual({token})});
  it("uses PUT, CSRF, scope, version and idempotency for project settings",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({display_name:"Store",locale:"en",timezone:"UTC",notifications:{payment_succeeded:true,payment_failed:true,weekly_summary:false},allowed_embed_origins:[],updated_at:"2026-08-11T00:00:00Z",version:3}),{status:200,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);await client.updateProjectSettings({tenantId:"tenant",merchantId:"merchant"},{version:2,display_name:"Store",locale:"en",timezone:"UTC",notifications:{payment_succeeded:true,payment_failed:true,weekly_summary:false},allowed_embed_origins:[],reason:"Profile reviewed"},"settings-update-1");const[,options]=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]??[];expect(options?.method).toBe("PUT");const headers=options?.headers as Headers;expect(headers.get("X-CSRF-Token")).toHaveLength(43);expect(headers.get("Idempotency-Key")).toBe("settings-update-1");expect(headers.get("X-Admin-Merchant-ID")).toBe("merchant");expect(JSON.parse(String(options?.body))).toMatchObject({version:2,reason:"Profile reviewed"})});
  it("keeps financial commands tenant-only, exact and idempotent across retry",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({data:{id:"10000000-0000-4000-8000-000000000001"}}),{status:200,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);const scope={tenantId:"tenant",merchantId:"merchant"};const id="10000000-0000-4000-8000-000000000001";for(let attempt=0;attempt<2;attempt+=1)await client.decideFinancialSweep(scope,id,"approve",7,"Independent evidence verified","financial-retry-0001");const calls=fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>;expect(calls).toHaveLength(2);for(const[url,options]of calls){const headers=options?.headers as Headers;expect(String(url)).toBe(`https://admin.invalid/admin/v1/financial/sweeps/${id}/approve`);expect(options?.method).toBe("POST");expect(options?.credentials).toBe("include");expect(options?.redirect).toBe("error");expect(headers.get("X-Admin-Tenant-ID")).toBe("tenant");expect(headers.get("X-Admin-Merchant-ID")).toBeNull();expect(headers.get("Idempotency-Key")).toBe("financial-retry-0001");expect(headers.get("Financial-Permissions")).toBeNull();expect(headers.get("Financial-Assertion")).toBeNull();expect(JSON.parse(String(options?.body))).toEqual({expected_version:7,reason:"Independent evidence verified"})}});
  it("preserves uint256 financial inputs as strings",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({data:{id:"10000000-0000-4000-8000-000000000001"}}),{status:201,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);const maximum="115792089237316195423570985008687907853269984665640564039457584007913129639935";await client.createFinancialSweep({tenantId:"tenant",merchantId:"merchant"},{asset_id:"usdt",destination:{chain:"tron",value:"destination"},sources:[{address:{chain:"tron",value:"source"},available:maximum,nonce_ref:"42"}],fee_quote:"1"},"financial-create-1");const options=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]?.[1];const body=JSON.parse(String(options?.body));expect(body.sources[0].available).toBe(maximum);expect(typeof body.sources[0].available).toBe("string");expect(body.fee_quote).toBe("1")});
  it("submits private hosted bootstrap evidence only as write input",async()=>{const response={id:"10000000-0000-4000-8000-000000000001",binding_id:"20000000-0000-4000-8000-000000000001",tenant_id:"30000000-0000-4000-8000-000000000001",policy_version:1,policies:{},payload_hash:"a".repeat(64),status:"pending_approval",expected_binding_version:1,reason:"Reviewed provider policy",requested_by:"40000000-0000-4000-8000-000000000001",created_at:"2026-08-11T00:00:00Z",expires_at:"2026-08-11T00:30:00Z",updated_at:"2026-08-11T00:00:00Z",row_version:1};const fetcher=vi.fn(async()=>new Response(JSON.stringify(response),{status:202,headers:{"Content-Type":"application/json"}}));const client=build(fetcher as typeof fetch);const parameters={timeout_ms:1000,max_attempts:2,backoff_ms:100,rate_limit:10,rate_window_seconds:60,max_health_age_seconds:120,failure_threshold:3,open_seconds:60,half_open_successes:2,priority:1,max_lag_blocks:0,failure_domain:"region-a"};const policies={health:parameters,create:parameters,status:parameters,cancel:parameters,refund:parameters,reconciliation:parameters};const returned=await client.requestProviderPolicy({tenantId:"30000000-0000-4000-8000-000000000001"},"20000000-0000-4000-8000-000000000001",1,policies,"bootstrap-reference-1","Reviewed provider policy","provider-policy-request-1");const[url,options]=(fetcher.mock.calls as unknown as Array<[RequestInfo|URL,RequestInit?]>)[0]??[];expect(String(url)).toContain("/admin/v1/providers/20000000-0000-4000-8000-000000000001/policy-requests");expect(JSON.parse(String(options?.body)).bootstrap_probe_reference).toBe("bootstrap-reference-1");expect(JSON.stringify(returned)).not.toContain("bootstrap-reference-1");expect(JSON.stringify(returned)).not.toContain("bootstrap_probe_reference")});
  it("keeps provider configuration references write-only and tenant-scoped", async () => {
    const response = {
      id: "10000000-0000-4000-8000-000000000001",
      provider_id: "hosted-primary",
      tenant_id: "30000000-0000-4000-8000-000000000001",
      merchant_id: "40000000-0000-4000-8000-000000000001",
      manifest_version: 1,
      change_kind: "provision",
      expected_head_version: 0,
      status: "pending_approval",
      adapter_kind: "hmac_json_v1",
      asset_id: "usdt",
      asset_decimals: 6,
      currency: "USD",
      api_key_id: "outbound-v1",
      callback_key_id: "callback-v1",
      callback_overlap_seconds: 0,
      payload_hash: "a".repeat(64),
      reason: "Provision reviewed provider",
      requested_by: "50000000-0000-4000-8000-000000000001",
      created_at: "2026-08-11T00:00:00Z",
      expires_at: "2026-08-11T00:30:00Z",
      head_version: 0,
      row_version: 1,
    };
    const fetcher = vi.fn(async () => new Response(JSON.stringify(response), {
      status: 202,
      headers: { "Content-Type": "application/json" },
    }));
    const client = build(fetcher as typeof fetch);
    const returned = await client.requestProviderConfiguration(
      { tenantId: response.tenant_id, merchantId: response.merchant_id },
      "hosted-primary",
      {
        merchant_id: response.merchant_id,
        expected_head_version: 0,
        change_kind: "provision",
        adapter_kind: "hmac_json_v1",
        api_origin: "https://private.provider.example",
        create_path: "/create",
        cancel_path: "/cancel",
        status_path: "/status",
        refund_path: "/refund",
        reconcile_path: "/reconcile",
        payment_url_origins: ["https://pay.provider.example"],
        api_credential_ref: "provider-outbound-v1",
        api_key_id: "outbound-v1",
        callback_secret_ref: "provider-callback-v1",
        callback_key_id: "callback-v1",
        signature_scheme: "hmac-sha256",
        asset_id: "usdt",
        asset_decimals: 6,
        currency: "USD",
        callback_overlap_seconds: 0,
        probe_reference: "health-reference-v1",
        reason: "Provision reviewed provider",
      },
      "provider-config-request-1",
    );
    const [url, options] = (fetcher.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>)[0] ?? [];
    const headers = options?.headers as Headers;
    const body = JSON.parse(String(options?.body));
    expect(String(url)).toBe("https://admin.invalid/admin/v1/provider-configurations/hosted-primary/requests");
    expect(headers.get("X-Admin-Tenant-ID")).toBe(response.tenant_id);
    expect(headers.get("X-Admin-Merchant-ID")).toBeNull();
    expect(headers.get("Idempotency-Key")).toBe("provider-config-request-1");
    expect(body.api_credential_ref).toBe("provider-outbound-v1");
    expect(body.callback_secret_ref).toBe("provider-callback-v1");
    expect(body.probe_reference).toBe("health-reference-v1");
    expect(JSON.stringify(returned)).not.toContain("provider-outbound-v1");
    expect(JSON.stringify(returned)).not.toContain("private.provider.example");
    expect(JSON.stringify(returned)).not.toContain("health-reference-v1");
  });
});
