using System.Security.Cryptography;
// Configure Kestrel/IIS body limits. Do not bind JSON before preserving raw bytes.
static class MerchantWebhookEndpoint {
  public static async Task<IResult> Accept(HttpRequest request,IVerifier verifier,IDatabase db){
    if(request.ContentLength is > 1048576)return Results.Json(new{error="invalid_body"},statusCode:413);using var memory=new MemoryStream();await request.Body.CopyToAsync(memory);var rawBody=memory.ToArray();if(rawBody.Length==0||rawBody.Length>1048576)return Results.Json(new{error="invalid_body"},statusCode:413);
    var verified=verifier.Verify(rawBody,request.Headers["Merchant-Webhook-Signature"]!,request.Headers["Content-Digest"]!);var digest=Convert.ToHexString(SHA256.HashData(rawBody)).ToLowerInvariant();
    var status=await db.Transaction(async tx=>{var existing=await tx.One("SELECT body_sha256 FROM merchant_webhook_inbox WHERE event_id=@event_id FOR UPDATE",new{event_id=verified.EventId});if(existing is not null)return CryptographicOperations.FixedTimeEquals(System.Text.Encoding.ASCII.GetBytes(existing.body_sha256),System.Text.Encoding.ASCII.GetBytes(digest))?200:409;await tx.Exec("INSERT INTO merchant_webhook_inbox(event_id,body_sha256,event_type) VALUES(@event_id,@digest,@type)",new{event_id=verified.EventId,digest,type=verified.EventType});if(verified.EventType=="payment.settled"){var order=await tx.One("SELECT * FROM commerce_orders WHERE merchant_order_id=@id FOR UPDATE",new{id=verified.OrderId});if(order is null||order.expected_amount_minor!=verified.AmountMinor||order.expected_currency!=verified.Currency)throw new InvalidOperationException("settlement does not match local order");await tx.Exec("UPDATE commerce_orders SET state='paid',paid_event_id=@event WHERE id=@id AND state='awaiting_payment'",new{event=verified.EventId,id=order.id});await tx.Exec("INSERT INTO fulfillment_outbox(id,event_id,order_id,kind,payload) VALUES(gen_random_uuid(),@event,@order,'fulfill_order','{}') ON CONFLICT(event_id) DO NOTHING",new{event=verified.EventId,order=order.id});}return 200;});
    return status==409?Results.Conflict(new{error="event_digest_conflict"}):Results.Json(new{acknowledged_event_id=verified.EventId});
  }
}
interface IVerifier{Verified Verify(byte[]raw,string signature,string digest);}record Verified(string EventId,string EventType,string OrderId,string AmountMinor,string Currency);interface IDatabase{Task<int>Transaction(Func<dynamic,Task<int>>work);}
