import { useI18n } from "@merchant/i18n";
import { Button, Input, PageHeader, SectionCard, Select, StatusBadge } from "@merchant/ui";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { GitCompareArrows, RefreshCw } from "lucide-react";
import { type FormEvent, useState } from "react";
import { isStepUpError, useAdmin } from "./AdminProvider";
import type { ManagementPage, MatchingPolicyChange, MatchingPolicyInput } from "./api/types";

type Notice="success"|"failure"|"stepup"|null;
type AsyncAction =
  () =>
  Promise<unknown>;
function commandKey(){return `matching-${crypto.randomUUID()}`}
function displayDate(value:string|undefined,locale:string){if(!value)return "—";const instant=Date.parse(value);return Number.isFinite(instant)?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(instant):value}

export function MatchingPolicyPage(){
  const {locale,t}=useI18n();const admin=useAdmin();const cache=useQueryClient();
  const [selectedId,setSelectedId]=useState("");const [reason,setReason]=useState("");const [effectiveAt,setEffectiveAt]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<Notice>(null);
  const [validation,setValidation]=useState(false);
  const [previewTolerance,setPreviewTolerance]=useState(500);
  const canRead=admin.can("matching_policy:read");
  const policies=useQuery<ManagementPage<MatchingPolicyChange>,Error>({queryKey:["admin","matching-policies",admin.scope?.tenantId,admin.scope?.merchantId],enabled:!admin.preview&&Boolean(admin.scope)&&canRead,queryFn:({signal})=>admin.clientFor(signal).matchingPolicies(admin.scope!,"",50,signal)});
  const policyRows=Array.isArray(policies.data?.data)?policies.data.data:[];
  const listSelected=policyRows.find(item=>item.id===selectedId)??policyRows[0];
  const detail=useQuery<MatchingPolicyChange,Error>({queryKey:["admin","matching-policy",admin.scope?.tenantId,admin.scope?.merchantId,listSelected?.id],enabled:!admin.preview&&Boolean(admin.scope&&listSelected)&&canRead,queryFn:({signal})=>admin.clientFor(signal).matchingPolicy(admin.scope!,listSelected!.id,signal)});
  const selected=detail.data??listSelected;const own=(selected?.requested_by??selected?.created_by)===admin.principal?.user_id;
  const refresh=()=>Promise.all([cache.invalidateQueries({queryKey:["admin","matching-policies"]}),cache.invalidateQueries({queryKey:["admin","matching-policy"]})]);
  const mutate=async(action:AsyncAction)=>{setBusy(true);setNotice(null);try{await action();setNotice("success");await refresh()}catch(error){setNotice(isStepUpError(error)?"stepup":"failure")}finally{setBusy(false)}};
  const create=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!admin.scope||!admin.can("matching_policy:write"))return;const data=new FormData(event.currentTarget);const tolerancePercent=Number(data.get("underpayment_tolerance_percent"));const input:MatchingPolicyInput={accumulate_partials:data.has("accumulate_partials"),underpayment_tolerance_bps:Math.round(tolerancePercent*100),overpayment_mode:String(data.get("overpayment_mode")) as MatchingPolicyInput["overpayment_mode"],accept_late_within_grace:data.has("accept_late_within_grace"),require_same_sender:data.has("require_same_sender"),gasfree_enabled:data.has("gasfree_enabled"),gasfree_fee_collectors:String(data.get("gasfree_fee_collectors")??"").split(",").map(value=>value.trim()).filter(Boolean)};if(!Number.isFinite(tolerancePercent)||tolerancePercent<0||tolerancePercent>100||(input.gasfree_enabled&&input.gasfree_fee_collectors.length===0)){setValidation(true);return}setValidation(false);if(admin.preview){setPreviewTolerance(input.underpayment_tolerance_bps);setNotice("success");return}void mutate(()=>admin.client!.createMatchingPolicy(admin.scope!,input,commandKey()))};
  const advance=(action:"request-approval"|"approve")=>{if(!admin.scope||!selected||reason.trim().length<8)return;void mutate(()=>admin.client!.mutateMatchingPolicy(admin.scope!,selected.id,action,selected.version,reason.trim(),commandKey()))};
  const activate=()=>{if(!admin.scope||!selected||reason.trim().length<8||!effectiveAt)return;void mutate(()=>admin.client!.activateMatchingPolicy(admin.scope!,selected.id,selected.version,reason.trim(),new Date(effectiveAt).toISOString(),commandKey()))};
  const previewPolicy:MatchingPolicyChange={id:"0198a100-0000-7000-8000-000000000041",proposed_version:1,accumulate_partials:true,underpayment_tolerance_bps:previewTolerance,overpayment_mode:"credit_expected_hold_excess",accept_late_within_grace:false,require_same_sender:false,gasfree_enabled:false,gasfree_fee_collectors:[],status:"activated",created_by:admin.principal?.user_id??"preview",activated_by:admin.principal?.user_id,effective_at:"2026-08-11T00:00:00Z",created_at:"2026-08-11T00:00:00Z",updated_at:"2026-08-11T00:00:00Z",version:1};
  const rows=admin.preview?[previewPolicy]:policyRows;
  const visibleSelected=admin.preview?previewPolicy:selected;
  const statusLabel=(status:MatchingPolicyChange["status"])=>t(({draft:"matching.statusDraft",pending_approval:"matching.statusPending",approved:"matching.statusApproved",activated:"matching.statusActivated",rejected:"matching.statusRejected"} as const)[status]);
  const modeLabel=(mode:MatchingPolicyInput["overpayment_mode"])=>t(({manual_review:"matching.manualReview",credit_all:"matching.creditAll",credit_expected_hold_excess:"matching.creditExpected"} as const)[mode]);
  return <div className="admin-page"><PageHeader actions={<Button disabled={admin.preview} onClick={()=>void policies.refetch()} variant="secondary"><RefreshCw size={15}/>{t("common.refresh")}</Button>} description={t("matching.body")} eyebrow={<><GitCompareArrows size={13}/>{t("matching.deterministic")}</>} title={t("matching.title")}/>{notice&&<div aria-live="polite" className={`admin-live-notice is-${notice}`} role={notice==="failure"?"alert":"status"}>{t(notice==="success"?"admin.mutationSucceeded":notice==="stepup"?"admin.stepUpBody":"admin.mutationFailed")}{notice==="stepup"&&<a href={admin.client?.stepUpURL(`${window.location.pathname}${window.location.hash}`)}>{t("admin.stepUp")}</a>}</div>}
    {admin.can("matching_policy:write")&&<SectionCard title={t("matching.createDraft")}><form className="admin-management-form" onSubmit={create}><label><span>{t("matching.toleranceBps")}</span><Input defaultValue="5" max={100} min={0} name="underpayment_tolerance_percent" required step="0.01" type="number"/><small>{t("matching.toleranceRange")}</small></label><label><span>{t("matching.overpaymentMode")}</span><Select defaultValue="credit_expected_hold_excess" name="overpayment_mode"><option value="manual_review">{t("matching.manualReview")}</option><option value="credit_all">{t("matching.creditAll")}</option><option value="credit_expected_hold_excess">{t("matching.creditExpected")}</option></Select></label><label className="admin-live-checks"><input defaultChecked name="accumulate_partials" type="checkbox"/>{t("matching.accumulatePartials")}</label><label className="admin-live-checks"><input name="accept_late_within_grace" type="checkbox"/>{t("matching.acceptLate")}</label><label className="admin-live-checks"><input name="require_same_sender" type="checkbox"/>{t("matching.sameSender")}</label><label className="admin-live-checks"><input name="gasfree_enabled" type="checkbox"/>{t("matching.gasfree")}</label><label className="is-wide"><span>{t("matching.collectors")}</span><Input aria-invalid={validation||undefined} name="gasfree_fee_collectors"/></label>{validation&&<p className="admin-management-approval-note is-wide" role="alert">{t("matching.collectorRequired")}</p>}<div className="is-wide"><Button disabled={busy} type="submit">{t("matching.createDraft")}</Button></div></form></SectionCard>}
    {!canRead&&<div className="admin-live-state" role="status"><strong>{t("admin.permissionTitle")}</strong><p>{t("admin.permissionBody")}</p></div>}
    {canRead&&!admin.preview&&policies.isLoading&&<div aria-busy="true" className="admin-live-state"><strong>{t("admin.dataLoading")}</strong></div>}
    {canRead&&!admin.preview&&policies.error&&<div className="admin-live-state" role="alert"><strong>{t("admin.dataError")}</strong></div>}
    {canRead&&!admin.preview&&!policies.isLoading&&!policies.error&&rows.length===0&&<div className="admin-live-state"><strong>{t("admin.emptyTitle")}</strong><p>{t("admin.emptyBody")}</p></div>}
    {canRead&&rows.length>0&&<div className="admin-platform-columns"><SectionCard title={t("matching.changes")}><div className="admin-platform-items">{rows.map(item=><button aria-label={`${t("matching.version",{version:item.proposed_version})}: ${statusLabel(item.status)}`} aria-pressed={visibleSelected?.id===item.id} key={item.id} onClick={()=>setSelectedId(item.id)} type="button"><span><strong>{t("matching.version",{version:item.proposed_version})}</strong><small>{displayDate(item.updated_at,locale)}</small></span><StatusBadge status={item.status}>{statusLabel(item.status)}</StatusBadge></button>)}</div></SectionCard>{visibleSelected&&<SectionCard title={t("matching.selected")}><dl className="admin-live-facts"><div><dt>{t("common.status")}</dt><dd><StatusBadge status={visibleSelected.status}>{statusLabel(visibleSelected.status)}</StatusBadge></dd></div><div><dt>{t("admin.objectVersion")}</dt><dd>{visibleSelected.version}</dd></div><div><dt>{t("matching.toleranceBps")}</dt><dd>{(visibleSelected.underpayment_tolerance_bps/100).toLocaleString(locale,{maximumFractionDigits:2})}%</dd></div><div><dt>{t("matching.overpaymentMode")}</dt><dd>{modeLabel(visibleSelected.overpayment_mode)}</dd></div><div><dt>{t("management.requester")}</dt><dd><code>{visibleSelected.requested_by??visibleSelected.created_by}</code></dd></div><div><dt>{t("matching.effectiveAt")}</dt><dd>{displayDate(visibleSelected.effective_at,locale)}</dd></div></dl>{!admin.preview&&own&&visibleSelected.status==="pending_approval"&&<p className="admin-management-approval-note">{t("matching.secondOperator")}</p>}{!admin.preview&&<><label className="admin-live-label"><span>{t("admin.reason")}</span><textarea maxLength={1000} minLength={8} onChange={event=>setReason(event.target.value)} rows={3} value={reason}/><small>{t("matching.reasonMinimum")}</small></label><div className="admin-live-actions">{visibleSelected.status==="draft"&&admin.can("matching_policy:write")&&<Button disabled={busy||reason.trim().length<8} onClick={()=>advance("request-approval")}>{t("matching.requestApproval")}</Button>}{visibleSelected.status==="pending_approval"&&admin.can("matching_policy:approve")&&<Button disabled={busy||own||reason.trim().length<8} onClick={()=>advance("approve")}>{t("matching.approve")}</Button>}{visibleSelected.status==="approved"&&admin.can("matching_policy:activate")&&<><label><span>{t("matching.effectiveAt")}</span><Input onChange={event=>setEffectiveAt(event.target.value)} type="datetime-local" value={effectiveAt}/></label><Button disabled={busy||reason.trim().length<8||!effectiveAt} onClick={activate}>{t("matching.activate")}</Button></>}</div></>}</SectionCard>}</div>}
  </div>;
}
