import { useI18n } from "@merchant/i18n";
import { Badge, Button, Input, PageHeader, SectionCard, Select, StatusBadge, ThemeToggle } from "@merchant/ui";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, CircleDollarSign, FileClock, GitCompareArrows, KeyRound, Save, Settings2, ShieldCheck, UserPlus, UsersRound, Webhook } from "lucide-react";
import { type FormEvent, useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { isStepUpError, useAdmin } from "./AdminProvider";
import { AdminAPIError } from "./api/client";
import type { MerchantInvitation, MerchantMember, MerchantProjectSettings, MerchantRoleKey, MerchantSecurityAction, OrdinaryMerchantRoleKey, Permission } from "./api/types";
import { invitationIdempotencyStorageKey, invitationPhaseStorageKey, invitationTokenStorageKey, validInvitationToken } from "./invitation-token";

type Notice = "success"|"failure"|"stepup"|null;
type AsyncAction =
  () =>
  Promise<unknown>;
const ordinaryRoles:OrdinaryMerchantRoleKey[]=["admin","developer","support","viewer"];
const allRoles:MerchantRoleKey[]=["owner","security_admin",...ordinaryRoles];
const highRiskRoles=new Set<MerchantRoleKey>(["owner","security_admin"]);
const memberStatusKeys={active:"merchant.memberActive",disabled:"merchant.memberDisabled",removed:"merchant.memberRemoved"} as const;
const invitationStatusKeys={pending_delivery:"merchant.invitePending",active:"merchant.inviteActive",accepted:"merchant.inviteAccepted",revoked:"merchant.inviteRevoked",expired:"merchant.inviteExpired"} as const;
const actionStatusKeys={pending_approval:"merchant.actionPending",completed:"merchant.actionCompleted",rejected:"merchant.actionRejected",expired:"merchant.actionExpired",failed:"merchant.actionFailed"} as const;
const roleKeys={owner:"merchant.roleOwner",security_admin:"merchant.roleSecurityAdmin",admin:"merchant.roleAdmin",developer:"merchant.roleDeveloper",support:"merchant.roleSupport",viewer:"merchant.roleViewer"} as const;

function idem(){return `merchant-admin-${crypto.randomUUID()}`}
function date(value:string,locale:string){return new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function State({loading,error,empty}:{loading:boolean;error:unknown;empty:boolean}){
  const{t}=useI18n();
  if(loading)return <div aria-busy="true" className="admin-live-state" role="status"><strong>{t("admin.dataLoading")}</strong></div>;
  if(error)return <div className="admin-live-state" role="alert"><strong>{t("admin.dataError")}</strong><p>{t("admin.dataErrorBody")}</p></div>;
  if(empty)return <div className="admin-live-state" role="status"><strong>{t("admin.emptyTitle")}</strong><p>{t("admin.emptyBody")}</p></div>;
  return null;
}
function NoticeBox({notice}:{notice:Notice}){const{t}=useI18n();const admin=useAdmin();if(!notice)return null;return <div aria-live="polite" className={`admin-live-notice is-${notice}`} role={notice==="failure"?"alert":"status"}>{t(notice==="success"?"admin.mutationSucceeded":notice==="stepup"?"admin.stepUpBody":"admin.mutationFailed")}{notice==="stepup"&&<a href={admin.client?.stepUpURL(`${window.location.pathname}${window.location.hash}`)}>{t("admin.stepUp")}</a>}</div>}
function Reason({value,onChange}:{value:string;onChange:(value:string)=>void}){const{t}=useI18n();return <label className="admin-live-label"><span>{t("admin.reason")}</span><textarea aria-label={t("admin.reason")} minLength={8} onChange={(event)=>onChange(event.target.value)} required rows={3} value={value}/><small>{t("merchant.reasonHelp")}</small></label>}
function roleLabel(key:MerchantRoleKey,t:ReturnType<typeof useI18n>["t"]){return t(roleKeys[key])}

export function MerchantTeamPage(){
  const{locale,t}=useI18n();const admin=useAdmin();const cache=useQueryClient();const scope=admin.scope;const canRead=admin.can("team:read");const enabled=!admin.preview&&Boolean(scope?.merchantId)&&canRead;
  const roles=useQuery({queryKey:["merchant-team","roles",scope?.tenantId,scope?.merchantId],enabled,queryFn:({signal})=>admin.clientFor(signal).teamRoles(scope!,signal)});
  const members=useQuery({queryKey:["merchant-team","members",scope?.tenantId,scope?.merchantId],enabled,queryFn:({signal})=>admin.clientFor(signal).teamMembers(scope!,"",100,signal)});
  const invites=useQuery({queryKey:["merchant-team","invites",scope?.tenantId,scope?.merchantId],enabled,queryFn:({signal})=>admin.clientFor(signal).teamInvitations(scope!,"",100,signal)});
  const actions=useQuery({queryKey:["merchant-team","actions",scope?.tenantId,scope?.merchantId],enabled,queryFn:({signal})=>admin.clientFor(signal).teamSecurityActions(scope!,"",100,signal)});
  const current=members.data?.data.find((item)=>item.email.toLowerCase()===admin.principal?.email?.toLowerCase());
  const permissions=useMemo(()=>{const result=new Set<Permission>();for(const role of roles.data?.data??[])if(current?.role_keys.includes(role.key))for(const permission of role.permissions)result.add(permission);return result},[roles.data,current]);
  const can=(permission:Permission)=>permissions.has(permission);
  const[selected,setSelected]=useState<MerchantMember|null>(null);
  const[selectedRoles,setSelectedRoles]=useState<MerchantRoleKey[]>([]);
  const[reason,setReason]=useState("");
  const[notice,setNotice]=useState<Notice>(null);
  const[busy,setBusy]=useState(false);
  const[createdInvite,setCreatedInvite]=useState<MerchantInvitation|null>(null);
  useEffect(()=>{setSelected(null);setCreatedInvite(null);setNotice(null)},[scope?.tenantId,scope?.merchantId]);
  const refresh=async()=>{await Promise.all([cache.invalidateQueries({queryKey:["merchant-team"]}),cache.invalidateQueries({queryKey:["admin-session"]})])};
  const mutate=async(action:AsyncAction)=>{
    setBusy(true);setNotice(null);
    try{await action();setNotice("success");setReason("");await refresh()}
    catch(error){setNotice(isStepUpError(error)?"stepup":"failure")}
    finally{setBusy(false)}
  };
  const selectMember=(member:MerchantMember)=>{setSelected(member);setSelectedRoles(member.role_keys);setReason("")};
  const rolesAreHighRisk=(before:MerchantRoleKey[],after:MerchantRoleKey[])=>[...highRiskRoles].some((key)=>before.includes(key)!==after.includes(key));
  const submitRoles=(event:FormEvent)=>{event.preventDefault();if(!scope||!selected||reason.trim().length<8||selectedRoles.length===0)return;const highRisk=rolesAreHighRisk(selected.role_keys,selectedRoles);if(highRisk&&!can("team:security_request")){setNotice("failure");return}void mutate(()=>highRisk?admin.client!.requestTeamSecurityAction(scope,{operation:"member.roles.replace",target_member_id:selected.id,target_version:selected.version,desired_role_keys:selectedRoles,reason:reason.trim()},idem()):admin.client!.changeMemberRoles(scope,selected.id,selected.version,selectedRoles,reason.trim(),idem()))};
  const mutateMember=(action:"disable"|"remove")=>{if(!scope||!selected||reason.trim().length<8)return;const highRisk=selected.role_keys.some((role)=>highRiskRoles.has(role));if(highRisk&&!can("team:security_request")){setNotice("failure");return}void mutate(()=>highRisk?admin.client!.requestTeamSecurityAction(scope,{operation:`member.${action}`,target_member_id:selected.id,target_version:selected.version,desired_role_keys:[],reason:reason.trim()},idem()):admin.client!.mutateMember(scope,selected.id,action,selected.version,reason.trim(),idem()))};
  const invite=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!scope)return;const data=new FormData(event.currentTarget);const role=data.get("role") as OrdinaryMerchantRoleKey;const delivery=data.get("delivery") as "copy_once"|"email";const input={email:String(data.get("email")??"").trim(),role_keys:[role],delivery_mode:delivery,ttl_seconds:Number(data.get("ttl")),reason:String(data.get("reason")??"").trim()};if(input.reason.length<8)return;setBusy(true);setNotice(null);void admin.client!.createTeamInvitation(scope,input,idem()).then(async(value)=>{setCreatedInvite(value);setNotice("success");await refresh()}).catch((error)=>setNotice(isStepUpError(error)?"stepup":"failure")).finally(()=>setBusy(false))};
  const decide=(action:MerchantSecurityAction,decision:"approve"|"reject")=>{if(!scope||reason.trim().length<8)return;void mutate(()=>admin.client!.decideTeamSecurityAction(scope,action.id,decision,action.version,reason.trim(),idem()))};
  if(!canRead)return <div className="admin-page"><PageHeader description={t("page.team.description")} title={t("page.team.title")}/><div className="admin-live-state" role="status"><strong>{t("admin.permissionTitle")}</strong><p>{t("admin.permissionBody")}</p></div></div>;
  const loading=roles.isLoading||members.isLoading;const error=roles.error??members.error;
  return <div className="admin-page" data-testid="merchant-team-page"><PageHeader description={t("page.team.description")} title={t("page.team.title")}/><NoticeBox notice={notice}/><State empty={!loading&&!error&&(members.data?.data.length??0)===0} error={error} loading={loading}/>
    {(members.data?.data.length??0)>0&&<div className="admin-management-grid">{members.data!.data.map(member=><article className={`admin-management-card${selected?.id===member.id?" is-selected":""}`} key={member.id}><button aria-pressed={selected?.id===member.id} className="admin-management-card__select" onClick={()=>selectMember(member)} type="button"><span><strong>{member.display_name}</strong><small>{member.email}</small></span><StatusBadge status={member.status}>{t(memberStatusKeys[member.status])}</StatusBadge></button><div className="merchant-role-list">{member.role_keys.map(role=><Badge key={role} tone={highRiskRoles.has(role)?"warning":"neutral"}>{roleLabel(role,t)}</Badge>)}</div><small>{t("merchant.version",{version:member.version})} · {date(member.updated_at,locale)}</small></article>)}</div>}
    {selected&&can("team:manage")&&<SectionCard title={t("merchant.editMember")}><form className="admin-management-form" onSubmit={submitRoles}><fieldset className="merchant-role-fieldset"><legend>{t("merchant.roles")}</legend>{allRoles.map(role=><label key={role}><input checked={selectedRoles.includes(role)} onChange={(event)=>setSelectedRoles((current)=>event.target.checked?[...current,role]:current.filter((item)=>item!==role))} type="checkbox"/><span>{roleLabel(role,t)}</span>{highRiskRoles.has(role)&&<small>{t("merchant.highRisk")}</small>}</label>)}</fieldset><div className="is-wide"><Reason onChange={setReason} value={reason}/></div><div className="is-wide admin-live-actions"><Button disabled={busy||reason.trim().length<8||selectedRoles.length===0} type="submit">{rolesAreHighRisk(selected.role_keys,selectedRoles)?t("merchant.requestApproval"):t("common.save")}</Button>{selected.status==="active"&&<Button disabled={busy||reason.trim().length<8} onClick={()=>mutateMember("disable")} type="button" variant="danger">{t("merchant.disableMember")}</Button>}<Button disabled={busy||reason.trim().length<8} onClick={()=>mutateMember("remove")} type="button" variant="danger">{t("merchant.removeMember")}</Button></div></form></SectionCard>}
    {can("team:invite")&&<SectionCard title={t("team.invite")}><form className="admin-management-form" onSubmit={invite}><label><span>{t("merchant.email")}</span><Input name="email" required type="email"/></label><label><span>{t("team.role")}</span><Select name="role">{ordinaryRoles.map(role=><option key={role} value={role}>{roleLabel(role,t)}</option>)}</Select></label><label><span>{t("merchant.delivery")}</span><Select name="delivery"><option value="email">{t("merchant.deliveryEmail")}</option><option value="copy_once">{t("merchant.deliveryCopy")}</option></Select></label><label><span>{t("merchant.validFor")}</span><Select defaultValue="86400" name="ttl"><option value="3600">{t("merchant.oneHour")}</option><option value="86400">{t("merchant.oneDay")}</option><option value="604800">{t("merchant.oneWeek")}</option></Select></label><label className="is-wide"><span>{t("admin.reason")}</span><Input minLength={8} name="reason" required/></label><p className="is-wide admin-management-approval-note">{t("merchant.invitedIdentityEnrollment")}</p><Button disabled={busy} type="submit"><UserPlus size={15}/>{t("team.invite")}</Button></form></SectionCard>}
    {createdInvite?.invite_token&&<section className="admin-secret-panel" data-testid="invite-token"><Badge tone="warning">{t("management.oneTime")}</Badge><h2>{t("merchant.copyInviteNow")}</h2><p>{t("merchant.copyInviteBody")}</p><output tabIndex={0}><code>{`${window.location.origin}${window.location.pathname}#/invite?token=${createdInvite.invite_token}`}</code></output><div className="admin-live-actions"><Button onClick={()=>void navigator.clipboard.writeText(`${window.location.origin}${window.location.pathname}#/invite?token=${createdInvite.invite_token}`)} variant="secondary">{t("common.copy")}</Button><Button onClick={()=>setCreatedInvite(null)}>{t("management.saved")}</Button></div></section>}
    <SectionCard title={t("merchant.invitations")}><State empty={(invites.data?.data.length??0)===0} error={invites.error} loading={invites.isLoading}/><div className="admin-management-list">{invites.data?.data.map(invite=><article key={invite.id}><div><strong>{invite.email}</strong><small>{invite.role_keys.map(role=>roleLabel(role,t)).join(", ")}</small></div><StatusBadge status={invite.status}>{t(invitationStatusKeys[invite.status])}</StatusBadge><time>{date(invite.expires_at,locale)}</time>{can("team:invite")&&["active","pending_delivery"].includes(invite.status)&&<Button disabled={busy||reason.trim().length<8} onClick={()=>scope&&void mutate(()=>admin.client!.revokeTeamInvitation(scope,invite.id,invite.version,reason.trim(),idem()))} size="sm" variant="danger">{t("merchant.revokeInvite")}</Button>}</article>)}</div></SectionCard>
    <SectionCard title={t("merchant.securityActions")}><Reason onChange={setReason} value={reason}/><State empty={(actions.data?.data.length??0)===0} error={actions.error} loading={actions.isLoading}/><div className="admin-management-list">{actions.data?.data.map(action=><article key={action.id}><div><strong>{t(action.operation==="member.roles.replace"?"merchant.operationRoles":action.operation==="member.disable"?"merchant.operationDisable":"merchant.operationRemove")}</strong><small>{action.request_reason}</small></div><StatusBadge status={action.status}>{t(actionStatusKeys[action.status])}</StatusBadge><span>{t("merchant.requester",{id:action.requested_by})}</span>{can("team:security_approve")&&action.status==="pending_approval"&&action.requested_by!==admin.principal?.user_id&&<div className="admin-live-actions"><Button disabled={busy||reason.trim().length<8} onClick={()=>decide(action,"approve")} size="sm">{t("common.approve")}</Button><Button disabled={busy||reason.trim().length<8} onClick={()=>decide(action,"reject")} size="sm" variant="danger">{t("common.reject")}</Button></div>}{action.requested_by===admin.principal?.user_id&&action.status==="pending_approval"&&<small>{t("merchant.selfApprovalBlocked")}</small>}</article>)}</div></SectionCard>
  </div>
}

function SettingsHub(){
  const{t}=useI18n();const admin=useAdmin();
  const groups=[
    {title:t("financialSettings.title"),items:[
      admin.can("infrastructure:read")&&{href:"#/financial-settings",title:t("financialSettings.title"),body:t("financialSettings.description"),icon:CircleDollarSign},
      admin.can("matching_policy:read")&&{href:"#/matching-policies",title:t("nav.matchingPolicies"),body:t("matching.body"),icon:GitCompareArrows}
    ].filter(Boolean)},
    {title:t("nav.integration"),items:[
      admin.can("webhook_settings:read")&&{href:"#/webhooks",title:t("nav.webhooks"),body:t("management.webhooksBody"),icon:Webhook},
      admin.can("api_clients:read")&&{href:"#/api-clients",title:t("nav.apiKeys"),body:t("management.apiClientsBody"),icon:KeyRound}
    ].filter(Boolean)},
    {title:t("page.team.title"),items:[
      admin.can("team:read")&&{href:"#/team",title:t("nav.team"),body:t("page.team.description"),icon:UsersRound},
      admin.can("audit:read")&&{href:"#/audit",title:t("nav.audit"),body:t("page.audit.description"),icon:FileClock}
    ].filter(Boolean)}
  ].filter(group=>group.items.length>0);
  return <div className="settings-hub">{groups.map(group=><section className="settings-hub__group" key={group.title}><h2>{group.title}</h2><div className="settings-hub__links">{group.items.map((item)=>{if(!item)return null;const Icon=item.icon;return <a className="settings-hub__link" href={item.href} key={item.href}><span className="settings-hub__icon"><Icon aria-hidden="true" size={18}/></span><span><strong>{item.title}</strong><small>{item.body}</small></span><ArrowRight aria-hidden="true" size={17}/></a>})}</div></section>)}</div>
}

export function MerchantProjectSettingsPage(){
  const{t}=useI18n();const admin=useAdmin();const cache=useQueryClient();const scope=admin.scope;const canRead=admin.can("settings:read");const canWrite=admin.can("settings:write");const query=useQuery({queryKey:["merchant-settings",scope?.tenantId,scope?.merchantId],enabled:!admin.preview&&Boolean(scope?.merchantId)&&canRead,queryFn:({signal})=>admin.clientFor(signal).projectSettings(scope!,signal)});const[notice,setNotice]=useState<Notice>(null);const[busy,setBusy]=useState(false);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!scope||!query.data)return;const data=new FormData(event.currentTarget);const origins=String(data.get("origins")??"").split(/\r?\n/).map(value=>value.trim()).filter(Boolean);const input={version:query.data.version,display_name:String(data.get("display_name")??"").trim(),locale:String(data.get("locale")) as MerchantProjectSettings["locale"],timezone:String(data.get("timezone")??"").trim(),support_email:String(data.get("support_email")??"").trim()||undefined,notifications:{payment_succeeded:data.get("payment_succeeded")==="on",payment_failed:data.get("payment_failed")==="on",weekly_summary:data.get("weekly_summary")==="on"},allowed_embed_origins:origins,reason:String(data.get("reason")??"").trim()};if(input.reason.length<8)return;setBusy(true);setNotice(null);void admin.client!.updateProjectSettings(scope,input,idem()).then(async()=>{setNotice("success");await cache.invalidateQueries({queryKey:["merchant-settings"]})}).catch((error)=>setNotice(isStepUpError(error)?"stepup":"failure")).finally(()=>setBusy(false))};
  return <div className="admin-page" data-testid="merchant-settings-page"><PageHeader description={t("page.settings.description")} eyebrow={<><Settings2 size={13}/>{t("common.production")}</>} title={t("page.settings.title")}/><SettingsHub/><NoticeBox notice={notice}/>{canRead&&<State empty={!query.isLoading&&!query.error&&!query.data} error={query.error} loading={query.isLoading}/>} {query.data&&<SectionCard title={t("merchant.projectProfile")}><form className="admin-management-form" key={query.data.version} onSubmit={submit}><label><span>{t("merchant.displayName")}</span><Input defaultValue={query.data.display_name} disabled={!canWrite} maxLength={120} name="display_name" required/></label><label><span>{t("common.locale")}</span><Select defaultValue={query.data.locale} disabled={!canWrite} name="locale">{admin.principal&&["en","zh-CN","es","fr","de","ru"].map(value=><option key={value} value={value}>{value}</option>)}</Select></label><label><span>{t("merchant.timezone")}</span><Input defaultValue={query.data.timezone} disabled={!canWrite} maxLength={100} name="timezone" required/></label><label><span>{t("merchant.supportEmail")}</span><Input defaultValue={query.data.support_email} disabled={!canWrite} name="support_email" type="email"/></label><fieldset className="merchant-role-fieldset" disabled={!canWrite}><legend>{t("merchant.notifications")}</legend>{(["payment_succeeded","payment_failed","weekly_summary"] as const).map(key=><label key={key}><input defaultChecked={query.data.notifications[key]} name={key} type="checkbox"/><span>{t(key==="payment_succeeded"?"merchant.paymentSucceeded":key==="payment_failed"?"merchant.paymentFailed":"merchant.weeklySummary")}</span></label>)}</fieldset><label><span>{t("merchant.embedOrigins")}</span><textarea defaultValue={query.data.allowed_embed_origins.join("\n")} disabled={!canWrite} name="origins" rows={5}/><small>{t("merchant.embedOriginsHelp")}</small></label>{canWrite&&<><label className="is-wide"><span>{t("admin.reason")}</span><Input minLength={8} name="reason" required/></label><div className="is-wide admin-live-actions"><Button disabled={busy} type="submit"><Save size={15}/>{t("common.save")}</Button><Badge tone="neutral">{t("merchant.version",{version:query.data.version})}</Badge></div></>}</form></SectionCard>}<div className="webhook-security-strip"><span><ShieldCheck size={17}/></span><div><strong>{t("merchant.nonFinancialOnly")}</strong><p>{t("merchant.nonFinancialOnlyBody")}</p></div></div></div>
}

export function InvitationAcceptPage(){
  const{t}=useI18n();const admin=useAdmin();const[params]=useSearchParams();const navigate=useNavigate();const routeToken=params.get("token")??"";
  const[token]=useState(()=>{let stored="";try{stored=window.sessionStorage.getItem(invitationTokenStorageKey)??"";if(validInvitationToken(routeToken)){if(stored!==routeToken){window.sessionStorage.removeItem(invitationPhaseStorageKey);window.sessionStorage.removeItem(invitationIdempotencyStorageKey)}window.sessionStorage.setItem(invitationTokenStorageKey,routeToken);stored=routeToken}}catch{return ""}return stored});
  const[idempotencyKey]=useState(()=>{try{const stored=window.sessionStorage.getItem(invitationIdempotencyStorageKey);if(stored)return stored;const created=idem();window.sessionStorage.setItem(invitationIdempotencyStorageKey,created);return created}catch{return idem()}});
  const[oidcStarted,setOIDCStarted]=useState(()=>{try{return window.sessionStorage.getItem(invitationPhaseStorageKey)==="1"}catch{return false}});
  const[notice,setNotice]=useState<"idle"|"busy"|"success"|"failure">("idle");const valid=validInvitationToken(token);
  useEffect(()=>{if(routeToken)navigate("/invite",{replace:true})},[navigate,routeToken]);
  const canAccept=admin.sessionState==="ready"||oidcStarted;
  const proceed=()=>{if(!valid||!admin.client)return;setNotice("busy");if(!canAccept){void admin.client.beginInvitationLogin(token).then((authorizationURL)=>{window.sessionStorage.setItem(invitationPhaseStorageKey,"1");setOIDCStarted(true);window.location.assign(authorizationURL)}).catch(()=>setNotice("failure"));return}void admin.client.acceptTeamInvitation(token,idempotencyKey).then(async()=>{window.sessionStorage.removeItem(invitationTokenStorageKey);window.sessionStorage.removeItem(invitationPhaseStorageKey);window.sessionStorage.removeItem(invitationIdempotencyStorageKey);await admin.reloadIdentity().catch(()=>undefined);setNotice("success")}).catch((error)=>{if(error instanceof AdminAPIError&&error.status===401){window.sessionStorage.removeItem(invitationPhaseStorageKey);setOIDCStarted(false)}setNotice("failure")})};
  return <main className="admin-access merchant-invite-accept"><div className="admin-access__controls"><ThemeToggle label={t("common.theme")}/></div><section aria-busy={notice==="busy"||undefined} role={notice==="failure"?"alert":"status"}><UsersRound aria-hidden="true" size={30}/><h1>{t("merchant.acceptTitle")}</h1><p>{t("merchant.acceptBody")}</p><p>{t("merchant.invitedIdentityEnrollment")}</p>{!valid&&<p>{t("merchant.invalidInvite")}</p>}{notice==="success"?<><strong>{t("merchant.acceptedInvite")}</strong><a className="mp-button mp-button--primary mp-button--md" href={`${window.location.pathname}${window.location.search}`}>{t("merchant.openWorkspace")}</a></>:<Button disabled={!valid||notice==="busy"} onClick={proceed}>{t(notice==="busy"?"merchant.accepting":canAccept?"merchant.accept":"common.signIn")}</Button>}</section></main>
}
