import { useI18n } from "@merchant/i18n";
import { Button, Input, PageHeader, SectionCard, Select, StatusBadge } from "@merchant/ui";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, Settings2, ShieldAlert } from "lucide-react";
import { type FormEvent, useMemo, useState } from "react";
import { isStepUpError, useAdmin } from "./AdminProvider";
import type { ConfigKind, PlatformChange, PlatformChangeInput, PlatformPage, PlatformSnapshot } from "./api/types";

const kinds:ConfigKind[]=["tenant","merchant_environment","chain","asset_contract","wallet_pool","rpc_provider","rate_source","rate_policy","finality_policy","matching_policy","quota","notification_channel","feature_flag","maintenance_window"];
const kindKey={tenant:"platform.kindTenant",merchant_environment:"platform.kindMerchantEnvironment",chain:"platform.kindChain",asset_contract:"platform.kindAssetContract",wallet_pool:"platform.kindWalletPool",rpc_provider:"platform.kindRPCProvider",rate_source:"platform.kindRateSource",rate_policy:"platform.kindRatePolicy",finality_policy:"platform.kindFinalityPolicy",matching_policy:"platform.kindMatchingPolicy",quota:"platform.kindQuota",notification_channel:"platform.kindNotificationChannel",feature_flag:"platform.kindFeatureFlag",maintenance_window:"platform.kindMaintenanceWindow"} as const;
const statusKey={draft:"platform.statusDraft",approval_requested:"platform.statusApprovalRequested",approved:"platform.statusApproved",rejected:"platform.statusRejected",scheduled:"platform.statusScheduled",active:"platform.statusActive",superseded:"platform.statusSuperseded",cancelled:"platform.statusCancelled"} as const;
type Notice="success"|"failure"|"stepup"|null;
type AsyncAction =
  () =>
  Promise<unknown>;

function key(){return `platform-${crypto.randomUUID()}`}
function when(value:string|undefined,locale:string){if(!value)return "—";const instant=Date.parse(value);return Number.isFinite(instant)?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(instant):value}
function containsSensitiveKey(value:unknown):boolean{if(!value||typeof value!=="object")return false;return Object.entries(value).some(([entry,nested])=>/(secret|private.?key|mnemonic|seed|password|credential|token)/i.test(entry)||containsSensitiveKey(nested))}
function objectPayload(raw:string){const value:unknown=JSON.parse(raw);if(!value||typeof value!=="object"||Array.isArray(value)||containsSensitiveKey(value))throw new Error("invalid_secret_free_payload");return value as Record<string,unknown>}

function PermissionMessage(){const {t}=useI18n();return <div className="admin-live-state" role="status"><strong>{t("admin.permissionTitle")}</strong><p>{t("admin.permissionBody")}</p></div>}

export function PlatformControlPage(){
  const {locale,t}=useI18n();const admin=useAdmin();const cache=useQueryClient();
  const [kind,setKind]=useState<ConfigKind>("feature_flag");
  const [selectedId,setSelectedId]=useState("");
  const [snapshotId,setSnapshotId]=useState("");
  const [reason,setReason]=useState("");
  const [rollbackReason,setRollbackReason]=useState("");
  const [activateAt,setActivateAt]=useState("");
  const [fence,setFence]=useState("0");
  const [busy,setBusy]=useState(false);
  const [notice,setNotice]=useState<Notice>(null);
  const canRead=admin.can("platform_config:read");
  const changes=useQuery<PlatformPage<PlatformChange>,Error>({queryKey:["admin","platform-changes",admin.scope?.tenantId,kind],enabled:!admin.preview&&admin.sessionState==="ready"&&Boolean(admin.scope)&&canRead,queryFn:({signal})=>admin.clientFor(signal).platformChanges(admin.scope!,{kind},signal)});
  const snapshots=useQuery<PlatformPage<PlatformSnapshot>,Error>({queryKey:["admin","platform-snapshots",admin.scope?.tenantId,kind],enabled:!admin.preview&&admin.sessionState==="ready"&&Boolean(admin.scope)&&canRead,queryFn:({signal})=>admin.clientFor(signal).platformSnapshots(admin.scope!,{kind},signal)});
  const changeRows=Array.isArray(changes.data?.items)?changes.data.items:[];const snapshotRows=Array.isArray(snapshots.data?.items)?snapshots.data.items:[];
  const selected=useMemo(()=>changeRows.find(item=>item.id===selectedId)??changeRows[0],[changeRows,selectedId]);const snapshot=useMemo(()=>snapshotRows.find(item=>item.id===snapshotId)??snapshotRows[0],[snapshotRows,snapshotId]);const own=selected?.requested_by===admin.principal?.user_id;
  const refresh=()=>Promise.all([cache.invalidateQueries({queryKey:["admin","platform-changes"]}),cache.invalidateQueries({queryKey:["admin","platform-snapshots"]})]);
  const mutate=async(action:AsyncAction)=>{setBusy(true);setNotice(null);try{await action();setNotice("success");await refresh()}catch(error){setNotice(isStepUpError(error)?"stepup":"failure")}finally{setBusy(false)}};
  const submitDraft=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!admin.scope||!admin.can("platform_config:write"))return;const data=new FormData(event.currentTarget);try{const input:PlatformChangeInput={tenant_id:admin.scope.tenantId,kind:String(data.get("kind")) as ConfigKind,logical_key:String(data.get("logical_key")??"").trim(),based_on_version:Number(data.get("based_on_version")),payload:objectPayload(String(data.get("payload")??"")),reason:String(data.get("reason")??"").trim()};void mutate(()=>admin.client!.createPlatformChange(admin.scope!,input,key()))}catch{setNotice("failure")}};
  const decide=(action:"request-approval"|"approve"|"reject")=>{if(!admin.scope||!selected||reason.trim().length<3)return;void mutate(()=>admin.client!.decidePlatformChange(admin.scope!,selected.id,action,{expected_row_version:selected.row_version,reason:reason.trim()},key()))};
  const schedule=()=>{if(!admin.scope||!selected||reason.trim().length<3||!activateAt)return;void mutate(()=>admin.client!.schedulePlatformChange(admin.scope!,selected.id,{expected_row_version:selected.row_version,reason:reason.trim(),activate_at:new Date(activateAt).toISOString()},key()))};
  const activate=()=>{if(!admin.scope||!selected||reason.trim().length<3)return;void mutate(()=>admin.client!.activatePlatformChange(admin.scope!,selected.id,{expected_row_version:selected.row_version,reason:reason.trim(),expected_fence_token:Number(fence)},key()))};
  const rollback=()=>{const scope=admin.scope;if(!scope||!snapshot||rollbackReason.trim().length<3)return;void mutate(()=>admin.client!.rollbackPlatformSnapshot(scope,{tenant_id:scope.tenantId,snapshot_id:snapshot.id,reason:rollbackReason.trim()},key()))};
  const emergency=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!admin.scope)return;const data=new FormData(event.currentTarget);void mutate(()=>admin.client!.emergencyPlatformPause(admin.scope!,{tenant_id:admin.scope!.tenantId,kind:String(data.get("kind")) as ConfigKind,logical_key:String(data.get("logical_key")??"").trim(),action:String(data.get("action")) as "pause"|"resume",reason:String(data.get("reason")??"").trim()},key()))};
  if(!canRead)return <div className="admin-page"><PageHeader description={t("platform.body")} eyebrow={<Settings2 size={13}/>} title={t("platform.title")}/><PermissionMessage/></div>;
  return <div className="admin-page">
    <PageHeader actions={<Button onClick={()=>void refresh()} variant="secondary"><RefreshCw size={15}/>{t("common.refresh")}</Button>} description={t("platform.body")} eyebrow={<><Settings2 size={13}/>{t("platform.controlPlane")}</>} title={t("platform.title")}/>
    <aside className="admin-platform-warning"><ShieldAlert size={18}/><div><strong>{t("platform.immutableWorkflow")}</strong><p>{t("platform.secretFreeBody")}</p></div></aside>
    {notice&&<div aria-live="polite" className={`admin-live-notice is-${notice}`} role={notice==="failure"?"alert":"status"}>{t(notice==="success"?"admin.mutationSucceeded":notice==="stepup"?"admin.stepUpBody":"admin.mutationFailed")}{notice==="stepup"&&<a href={admin.client?.stepUpURL(`${window.location.pathname}${window.location.hash}`)}>{t("admin.stepUp")}</a>}</div>}
    <div className="admin-platform-toolbar"><label><span>{t("platform.configKind")}</span><Select onChange={event=>setKind(event.target.value as ConfigKind)} value={kind}>{kinds.map(item=><option key={item} value={item}>{t(kindKey[item])}</option>)}</Select></label></div>
    {admin.can("platform_config:write")&&<SectionCard title={t("platform.createDraft")}><form className="admin-management-form" onSubmit={submitDraft}><label><span>{t("platform.configKind")}</span><Select name="kind" value={kind} onChange={event=>setKind(event.target.value as ConfigKind)}>{kinds.map(item=><option key={item} value={item}>{t(kindKey[item])}</option>)}</Select></label><label><span>{t("platform.logicalKey")}</span><Input name="logical_key" pattern="[a-z0-9][a-z0-9._:/-]*" required/></label><label><span>{t("platform.basedOnVersion")}</span><Input defaultValue="0" min={0} name="based_on_version" required type="number"/></label><label className="is-wide"><span>{t("platform.payloadJSON")}</span><textarea defaultValue="{}" name="payload" required rows={7}/><small>{t("platform.payloadHint")}</small></label><label className="is-wide"><span>{t("admin.reason")}</span><textarea maxLength={1000} minLength={3} name="reason" required rows={3}/></label><div className="is-wide"><Button disabled={busy} type="submit">{t("platform.createDraft")}</Button></div></form></SectionCard>}
    <div className="admin-platform-columns"><SectionCard title={t("platform.changes")}><div aria-busy={changes.isLoading||undefined} className="admin-platform-items">{changes.error&&<p role="alert">{t("admin.dataError")}</p>}{!changes.isLoading&&!changes.error&&changeRows.length===0&&<p>{t("admin.emptyBody")}</p>}{changeRows.map(item=><button aria-pressed={selected?.id===item.id} key={item.id} onClick={()=>setSelectedId(item.id)} type="button"><span><strong>{item.logical_key}</strong><small>{t(kindKey[item.kind])} · v{item.version}</small></span><StatusBadge status={item.status}>{t(statusKey[item.status])}</StatusBadge></button>)}</div></SectionCard><SectionCard title={t("platform.snapshots")}><div aria-busy={snapshots.isLoading||undefined} className="admin-platform-items">{snapshots.error&&<p role="alert">{t("admin.dataError")}</p>}{!snapshots.isLoading&&!snapshots.error&&snapshotRows.length===0&&<p>{t("admin.emptyBody")}</p>}{snapshotRows.map(item=><button aria-pressed={snapshot?.id===item.id} key={item.id} onClick={()=>setSnapshotId(item.id)} type="button"><span><strong>{item.logical_key}</strong><small>{t(kindKey[item.kind])} · v{item.version}</small></span><time>{when(item.activated_at,locale)}</time></button>)}</div></SectionCard></div>
    {selected&&<SectionCard title={t("platform.selectedChange")}><dl className="admin-live-facts"><div><dt>{t("common.status")}</dt><dd><StatusBadge status={selected.status}>{t(statusKey[selected.status])}</StatusBadge></dd></div><div><dt>{t("admin.objectVersion")}</dt><dd>{selected.row_version}</dd></div><div><dt>{t("platform.requestedBy")}</dt><dd><code>{selected.requested_by}</code></dd></div><div><dt>{t("platform.payloadHash")}</dt><dd><code>{selected.payload_hash}</code></dd></div></dl>{own&&<p className="admin-platform-separation">{t("platform.secondOperator")}</p>}<label className="admin-live-label"><span>{t("admin.reason")}</span><textarea onChange={event=>setReason(event.target.value)} rows={3} value={reason}/></label><div className="admin-live-actions">{selected.status==="draft"&&admin.can("platform_config:request")&&<Button disabled={busy||reason.trim().length<3} onClick={()=>decide("request-approval")}>{t("platform.requestApproval")}</Button>}{selected.status==="approval_requested"&&admin.can("platform_config:approve")&&<><Button disabled={busy||own||reason.trim().length<3} onClick={()=>decide("approve")}>{t("admin.approve")}</Button><Button disabled={busy||own||reason.trim().length<3} onClick={()=>decide("reject")} variant="danger">{t("admin.reject")}</Button></>}{selected.status==="approved"&&admin.can("platform_config:schedule")&&<><label><span>{t("platform.activateAt")}</span><Input onChange={event=>setActivateAt(event.target.value)} type="datetime-local" value={activateAt}/></label><Button disabled={busy||!activateAt||reason.trim().length<3} onClick={schedule}>{t("platform.schedule")}</Button></>}{selected.status==="scheduled"&&admin.can("platform_config:activate")&&<><label><span>{t("platform.expectedFence")}</span><Input min={0} onChange={event=>setFence(event.target.value)} type="number" value={fence}/></label><Button disabled={busy||reason.trim().length<3} onClick={activate}>{t("platform.activate")}</Button></>}</div></SectionCard>}
    {snapshot&&admin.can("platform_config:rollback")&&<SectionCard title={t("platform.rollback")}><p>{t("platform.rollbackBody",{key:snapshot.logical_key,version:snapshot.version})}</p><label className="admin-live-label"><span>{t("admin.reason")}</span><textarea onChange={event=>setRollbackReason(event.target.value)} rows={3} value={rollbackReason}/></label><Button disabled={busy||rollbackReason.trim().length<3} onClick={rollback} variant="secondary">{t("platform.createRollback")}</Button></SectionCard>}
    {admin.can("platform_config:emergency")&&<SectionCard title={t("platform.emergency")}><form className="admin-management-form" onSubmit={emergency}><label><span>{t("platform.configKind")}</span><Select name="kind">{kinds.map(item=><option key={item} value={item}>{t(kindKey[item])}</option>)}</Select></label><label><span>{t("platform.logicalKey")}</span><Input name="logical_key" required/></label><label><span>{t("platform.action")}</span><Select name="action"><option value="pause">{t("platform.pause")}</option><option value="resume">{t("platform.resume")}</option></Select></label><label className="is-wide"><span>{t("admin.reason")}</span><textarea maxLength={1000} minLength={8} name="reason" required rows={3}/></label><div className="is-wide"><Button disabled={busy} type="submit" variant="danger">{t("platform.recordEmergencyAction")}</Button></div></form></SectionCard>}
  </div>
}
