BEGIN;

DROP FUNCTION IF EXISTS fail_merchant_invitation_delivery(uuid,uuid,text,integer,integer);
DROP FUNCTION IF EXISTS complete_merchant_invitation_delivery(uuid,uuid,text);
DROP FUNCTION IF EXISTS claim_merchant_invitation_delivery(uuid,integer);
DROP FUNCTION IF EXISTS merchant_invitation_delivery_keys_admitted(text[]);
DROP FUNCTION IF EXISTS merchant_invitation_delivery_heartbeat(uuid);
DROP FUNCTION IF EXISTS append_merchant_settings_audit(uuid,uuid,uuid,uuid,uuid,uuid,text,text,text,text,jsonb,timestamptz);
DROP FUNCTION IF EXISTS consume_merchant_session_revocations(integer);
DROP TRIGGER IF EXISTS merchant_security_action_transition ON merchant_security_action_requests;
DROP FUNCTION IF EXISTS enforce_merchant_security_action_transition();
DROP TRIGGER IF EXISTS merchant_invitation_transition ON merchant_member_invitations;
DROP FUNCTION IF EXISTS enforce_merchant_invitation_transition();
DROP TRIGGER IF EXISTS merchant_last_owner_member_guard ON merchant_members;
DROP FUNCTION IF EXISTS guard_last_merchant_owner_member_status();
DROP TRIGGER IF EXISTS merchant_last_owner_guard ON merchant_member_role_bindings;
DROP FUNCTION IF EXISTS guard_last_merchant_owner();
DROP TRIGGER IF EXISTS merchant_settings_audit_immutable ON merchant_settings_audit_log;
DROP FUNCTION IF EXISTS reject_merchant_settings_audit_mutation();
DROP TRIGGER IF EXISTS merchant_settings_versions_immutable ON merchant_project_settings_versions;
DROP FUNCTION IF EXISTS reject_merchant_settings_history_mutation();
DROP TABLE IF EXISTS merchant_settings_audit_log;
DROP TABLE IF EXISTS merchant_settings_assertion_jtis;
DROP TABLE IF EXISTS merchant_settings_idempotency;
DROP TABLE IF EXISTS merchant_project_settings_versions;
DROP TABLE IF EXISTS merchant_project_settings;
DROP TABLE IF EXISTS merchant_session_revocation_signals;
ALTER TABLE merchant_member_role_bindings DROP CONSTRAINT IF EXISTS merchant_role_grant_request_fk;
ALTER TABLE merchant_member_role_bindings DROP CONSTRAINT IF EXISTS merchant_role_revoke_request_fk;
DROP TABLE IF EXISTS merchant_security_action_requests;
DROP FUNCTION IF EXISTS merchant_security_payload_hash(text,uuid,bigint,text[]);
DROP TABLE IF EXISTS merchant_invitation_delivery_workers;
DROP TABLE IF EXISTS merchant_invitation_delivery_jobs;
DROP TABLE IF EXISTS merchant_member_invitations;
DROP FUNCTION IF EXISTS lookup_merchant_invitation(bytea);
DROP TABLE IF EXISTS merchant_member_role_bindings;
DROP TABLE IF EXISTS merchant_members;
DROP TABLE IF EXISTS merchant_cabinet_role_permissions;
DROP TABLE IF EXISTS merchant_cabinet_roles;
DROP TABLE IF EXISTS merchant_cabinet_permissions;

COMMIT;
