BEGIN;
DELETE FROM admin_role_permissions WHERE permission_key LIKE 'platform_config:%';
DELETE FROM admin_permissions WHERE permission_key LIKE 'platform_config:%';
DROP TABLE IF EXISTS platform_admin_outbox CASCADE;
DROP TABLE IF EXISTS platform_admin_audit CASCADE;
DROP TABLE IF EXISTS platform_admin_idempotency CASCADE;
DROP TABLE IF EXISTS platform_emergency_pause_events CASCADE;
DROP TABLE IF EXISTS platform_config_activations CASCADE;
DROP TABLE IF EXISTS platform_config_heads CASCADE;
DROP TABLE IF EXISTS platform_config_snapshots CASCADE;
DROP TABLE IF EXISTS platform_config_change_requests CASCADE;
DROP FUNCTION IF EXISTS append_platform_admin_audit(uuid,uuid,uuid,text,text,text,text,text,jsonb,timestamptz);
DROP FUNCTION IF EXISTS platform_immutable_row();
DROP FUNCTION IF EXISTS consume_platform_admin_assertion(text,uuid,timestamptz);
DROP TABLE IF EXISTS platform_admin_assertion_nonces CASCADE;
DROP TABLE IF EXISTS platform_admin_service_identities CASCADE;
DROP FUNCTION IF EXISTS platform_payload_has_no_secrets(jsonb);
DROP FUNCTION IF EXISTS platform_exact_money_strings(jsonb);
DROP FUNCTION IF EXISTS platform_scope_uuid(uuid);
DROP TYPE IF EXISTS platform_change_status;
DROP TYPE IF EXISTS platform_config_kind;
COMMIT;
