BEGIN;
DROP FUNCTION IF EXISTS legacy_compat_ready(timestamptz);
DROP FUNCTION IF EXISTS legacy_fail_callback(uuid,uuid,bigint,text,integer,timestamptz);
DROP FUNCTION IF EXISTS legacy_ack_callback(uuid,uuid,bigint,integer,bytea,timestamptz);
DROP FUNCTION IF EXISTS legacy_claim_callbacks(text,integer,integer,timestamptz);
DROP FUNCTION IF EXISTS legacy_enqueue_callback(uuid,uuid,bigint,uuid,text,uuid,text,text,text,text,bytea,timestamptz);
DROP FUNCTION IF EXISTS legacy_classify_event(uuid,bigint,uuid,text,timestamptz);
DROP FUNCTION IF EXISTS legacy_list_event_sources(timestamptz);
DROP FUNCTION IF EXISTS legacy_lookup_mapping_by_intent(uuid,uuid);
DROP FUNCTION IF EXISTS legacy_lookup_mapping(text);
DROP FUNCTION IF EXISTS legacy_record_mapping(text,uuid,uuid,text,text,bytea,uuid,uuid,text,text,text,text,text,text,text,text,timestamptz);
DROP FUNCTION IF EXISTS legacy_lookup_credential_version(uuid);
DROP FUNCTION IF EXISTS legacy_lookup_credential(text,text,timestamptz);
DROP FUNCTION IF EXISTS approve_legacy_compat_config_admission(uuid,jsonb);
DROP FUNCTION IF EXISTS approve_legacy_compat_config_admission(uuid,bytea);
DROP FUNCTION IF EXISTS request_legacy_compat_config_admission(uuid,jsonb);
DROP FUNCTION IF EXISTS request_legacy_compat_config_admission(uuid,uuid,uuid,uuid,uuid,text,text,text,smallint,text,text,text,text,text,cidr[],text,text,text,text,timestamptz,timestamptz,timestamptz,jsonb,bytea);
DROP TRIGGER IF EXISTS legacy_attempt_immutable ON legacy_compat_callback_attempts;
DROP TRIGGER IF EXISTS legacy_classification_immutable ON legacy_compat_event_classifications;
DROP TRIGGER IF EXISTS legacy_mapping_immutable ON legacy_compat_mappings;
DROP TRIGGER IF EXISTS legacy_credential_immutable ON legacy_compat_credential_versions;
DROP FUNCTION IF EXISTS legacy_compat_reject_mutation();
DROP TRIGGER IF EXISTS legacy_admission_request_guard_trigger ON legacy_compat_admission_requests;
DROP FUNCTION IF EXISTS legacy_admission_request_guard();
DROP TABLE IF EXISTS legacy_compat_callback_attempts;
DROP TABLE IF EXISTS legacy_compat_callback_deliveries;
DROP TABLE IF EXISTS legacy_compat_event_classifications;
DROP TABLE IF EXISTS legacy_compat_event_cursors;
DROP TABLE IF EXISTS legacy_compat_mappings;
DROP TABLE IF EXISTS legacy_compat_admission_requests;
ALTER TABLE legacy_compat_configs DROP CONSTRAINT IF EXISTS legacy_config_current_credential_fk;
DROP TABLE IF EXISTS legacy_compat_credential_versions;
DROP TABLE IF EXISTS legacy_compat_configs;
COMMIT;
