<?php
declare(strict_types=1);

namespace MerchantPlatform;

final class MerchantApiException extends \RuntimeException {
    public function __construct(public readonly int $status, public readonly string $errorCode, string $message, public readonly ?string $requestId = null, public readonly ?array $details = null, public readonly bool $retryable = false, public readonly ?float $retryAfterSeconds = null) { parent::__construct($message); }
}

final class Client {
    public function __construct(private readonly string $baseUrl, private readonly string $keyId, private readonly string $secret, private readonly float $timeoutSeconds = 10.0) { self::validateBaseUrl($baseUrl); }
    public function createPaymentIntent(CreatePaymentIntentRequest $value, string $key): Envelope { return $this->intentEnvelope($this->request('POST','/v1/payment-intents',$value->toArray(),[],$key)); }
    public function listPaymentIntents(?string $status = null, ?string $after = null, int $limit = 50): Envelope { $value=$this->request('GET','/v1/payment-intents',null,['status'=>$status,'after'=>$after,'limit'=>$limit]); return new Envelope(new CursorPage(array_map([PaymentIntent::class,'fromArray'],$value['data']['items']),$value['data']['next_cursor'] ?? ''),$value['request_id'],$value['api_version']); }
    public function getPaymentIntent(string $id): Envelope { return $this->intentEnvelope($this->request('GET','/v1/payment-intents/'.rawurlencode($id))); }
    public function createPaymentRoute(string $intentId, CreatePaymentRouteRequest $value, string $key): Envelope { $raw=$this->request('POST','/v1/payment-intents/'.rawurlencode($intentId).'/routes',$value->toArray(),[],$key); return new Envelope(PaymentRoute::fromArray($raw['data']),$raw['request_id'],$raw['api_version']); }
    public function listPaymentRoutes(string $intentId): Envelope { $raw=$this->request('GET','/v1/payment-intents/'.rawurlencode($intentId).'/routes'); return new Envelope(array_map([PaymentRoute::class,'fromArray'],$raw['data']['items']),$raw['request_id'],$raw['api_version']); }
    public function cancelPaymentIntent(string $intentId, CancelPaymentIntentRequest $value, string $key): Envelope { return $this->intentEnvelope($this->request('POST','/v1/payment-intents/'.rawurlencode($intentId).'/cancel',$value->toArray(),[],$key)); }
    public function expirePaymentIntent(string $intentId, ExpirePaymentIntentRequest $value, string $key): Envelope { return $this->intentEnvelope($this->request('POST','/v1/payment-intents/'.rawurlencode($intentId).'/expire',$value->toArray(),[],$key)); }
    public function updatePaymentIntentMetadata(string $intentId, UpdatePaymentIntentMetadataRequest $value, string $key): Envelope { return $this->intentEnvelope($this->request('POST','/v1/payment-intents/'.rawurlencode($intentId).'/metadata',$value->toArray(),[],$key)); }
    public function listAssets(): Envelope { $raw=$this->request('GET','/v1/assets'); return new Envelope(array_map([Asset::class,'fromArray'],$raw['data']['items']),$raw['request_id'],$raw['api_version']); }
    public function submitPaymentProof(SubmitPaymentProofRequest $value, string $key): Envelope { return $this->proofEnvelope($this->request('POST','/v1/payment-proofs',$value->toArray(),[],$key)); }
    public function getPaymentProof(string $id): Envelope { return $this->proofEnvelope($this->request('GET','/v1/payment-proofs/'.rawurlencode($id))); }
    public function listEvents(int $afterSequence = 0, int $limit = 100): Envelope { $raw=$this->request('GET','/v1/events',null,['after_sequence'=>$afterSequence,'limit'=>$limit]); return new Envelope(new EventPage($raw['data']['items'],$raw['data']['next_cursor'],$raw['data']['next_sequence']),$raw['request_id'],$raw['api_version']); }
    public function getEvent(string $id): Envelope{return $this->mappingEnvelope($this->request('GET','/v1/events/'.rawurlencode($id)));}
    public function listTransfers(?string $after=null,int $limit=50): Envelope{return $this->pageEnvelope($this->request('GET','/v1/transfers',null,['after'=>$after,'limit'=>$limit]));}
    public function getTransferEvents(string $network,string $transactionId): Envelope{$raw=$this->request('GET','/v1/transfers/'.rawurlencode($network).'/'.rawurlencode($transactionId));return new Envelope($raw['data']['items'],$raw['request_id'],$raw['api_version']);}
    public function listQuotes(?string $after=null,int $limit=50): Envelope{return $this->pageEnvelope($this->request('GET','/v1/quotes',null,['after'=>$after,'limit'=>$limit]));}
    public function getQuote(string $id): Envelope{return $this->mappingEnvelope($this->request('GET','/v1/quotes/'.rawurlencode($id)));}
    public function listBalances(): Envelope{$raw=$this->request('GET','/v1/balances');return new Envelope($raw['data']['items'],$raw['request_id'],$raw['api_version']);}
    public function getReconciliation(): Envelope{return $this->mappingEnvelope($this->request('GET','/v1/reconciliation'));}
    public function createReconciliationReport(CreateReconciliationReportRequest $value,string $key): Envelope{return $this->mappingEnvelope($this->request('POST','/v1/reconciliation-reports',$value->toArray(),[],$key));}
    public function getReconciliationReport(string $id): Envelope{return $this->mappingEnvelope($this->request('GET','/v1/reconciliation-reports/'.rawurlencode($id)));}
    public function downloadReconciliationReport(string $id): ReportDownload{return $this->download('/v1/reconciliation-reports/'.rawurlencode($id).'/download');}
    public function createPaymentLink(array $value,string $key): array{return $this->request('POST','/v1/payment-links',$value,[],$key);}
    public function listPaymentLinks(?string $cursor=null,int $limit=50): array{return $this->request('GET','/v1/payment-links',null,['cursor'=>$cursor,'limit'=>$limit]);}
    public function getPaymentLink(string $id): array{return $this->request('GET','/v1/payment-links/'.rawurlencode($id));}
    public function disablePaymentLink(string $id,int $version,string $key): array{return $this->request('POST','/v1/payment-links/'.rawurlencode($id).'/disable',['version'=>$version],[],$key);}
    public function createCheckoutSession(array $value,string $key): array{return $this->request('POST','/v1/checkout-sessions',$value,[],$key);}
    private function request(string $method, string $path, ?array $payload = null, array $query = [], ?string $idempotencyKey = null): array {
        if ($idempotencyKey !== null && (strlen($idempotencyKey)<8 || strlen($idempotencyKey)>255)) throw new \InvalidArgumentException('idempotency key must be 8..255 characters');
        $encoded=Signing::canonicalQuery($query); $pathAndQuery=$path.($encoded!==''?'?'.$encoded:''); $body=$payload===null?'':json_encode($payload,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
        $signed=Signing::request($this->keyId,$this->secret,$method,$pathAndQuery,$body,time(),bin2hex(random_bytes(16))); $headers=['Accept: application/json']; foreach($signed->toArray() as $header=>$value)$headers[]=$header.': '.$value; if($payload!==null)$headers[]='Content-Type: application/json'; if($idempotencyKey!==null)$headers[]='Idempotency-Key: '.$idempotencyKey;
        [$status,$raw,$responseHeaders]=$this->send($method,rtrim($this->baseUrl,'/').$pathAndQuery,$headers,$payload===null?null:$body);
        try{$value=$raw===''?[]:json_decode($raw,true,512,JSON_THROW_ON_ERROR);}catch(\JsonException){throw new MerchantApiException($status,'invalid_response','server returned invalid JSON',$responseHeaders['request-id']??null);}
        if($status<200||$status>=300){$error=$value['error']??[];$retry=isset($responseHeaders['retry-after'])&&ctype_digit($responseHeaders['retry-after'])?min(300.0,(float)$responseHeaders['retry-after']):null;throw new MerchantApiException($status,$error['code']??'http_error',$error['message']??'API request failed',$value['request_id']??($responseHeaders['request-id']??null),$error['details']??null,$status===429||$status>=500,$retry);} return $value;
    }
    private function send(string $method,string $url,array $headers,?string $body): array {
        $context=stream_context_create(['http'=>['method'=>$method,'header'=>implode("\r\n",$headers),'content'=>$body??'','timeout'=>$this->timeoutSeconds,'ignore_errors'=>true,'follow_location'=>0,'max_redirects'=>0]]); $raw=@file_get_contents($url,false,$context);
        if($raw===false&&!isset($http_response_header))throw new MerchantApiException(0,'transport_error','request failed',retryable:true); $status=0;$parsed=[];foreach($http_response_header??[] as $line){if(preg_match('/^HTTP\/\S+\s+(\d+)/',$line,$match))$status=(int)$match[1];elseif(str_contains($line,':')){[$key,$value]=explode(':',$line,2);$parsed[strtolower(trim($key))]=trim($value);}}return[$status,$raw===false?'':$raw,$parsed];
    }
    private function download(string $path): ReportDownload{$maximum=268435456;$signed=Signing::request($this->keyId,$this->secret,'GET',$path,'',time(),bin2hex(random_bytes(16)));$headers=['Accept: application/x-ndjson'];foreach($signed->toArray()as$key=>$value)$headers[]=$key.': '.$value;$context=stream_context_create(['http'=>['method'=>'GET','header'=>implode("\r\n",$headers),'timeout'=>900,'ignore_errors'=>true,'follow_location'=>0,'max_redirects'=>0]]);$stream=@fopen(rtrim($this->baseUrl,'/').$path,'rb',false,$context);if($stream===false)throw new MerchantApiException(0,'transport_error','report download failed',retryable:true);$metadata=stream_get_meta_data($stream);$status=0;$responseHeaders=[];foreach($metadata['wrapper_data']??[]as$line){if(preg_match('/^HTTP\/\S+\s+(\d+)/',$line,$match))$status=(int)$match[1];elseif(str_contains($line,':')){[$key,$value]=explode(':',$line,2);$responseHeaders[strtolower(trim($key))]=trim($value);}}if($status!==200){fclose($stream);throw new MerchantApiException($status,'report_unavailable','reconciliation report unavailable',retryable:$status===429||$status>=500);}$raw='';while(!feof($stream)){$chunk=fread($stream,1048576);if($chunk===false){fclose($stream);throw new MerchantApiException(0,'transport_error','report download failed',retryable:true);}$raw.=$chunk;if(strlen($raw)>$maximum){fclose($stream);throw new MerchantApiException(200,'report_too_large','reconciliation report exceeds configured client limit');}}fclose($stream);$digest=$responseHeaders['x-reconciliation-sha256']??'';$signature=$responseHeaders['x-reconciliation-signature']??'';$keyId=$responseHeaders['x-reconciliation-signing-key-id']??'';if(!preg_match('/^[0-9a-f]{64}$/',$digest)||$signature===''||$keyId==='')throw new MerchantApiException(200,'invalid_response','missing reconciliation integrity headers');return new ReportDownload($raw,$digest,$signature,$keyId);}
    private function intentEnvelope(array $raw): Envelope{return new Envelope(PaymentIntent::fromArray($raw['data']),$raw['request_id'],$raw['api_version']);}
    private function proofEnvelope(array $raw): Envelope{return new Envelope(PaymentProof::fromArray($raw['data']),$raw['request_id'],$raw['api_version']);}
    private function mappingEnvelope(array $raw): Envelope{return new Envelope($raw['data'],$raw['request_id'],$raw['api_version']);}
    private function pageEnvelope(array $raw): Envelope{return new Envelope(new CursorPage($raw['data']['items'],$raw['data']['next_cursor']??''),$raw['request_id'],$raw['api_version']);}
    public static function validateBaseUrl(string $value): void{$parts=parse_url($value);$host=$parts['host']??'';$loopback=($parts['scheme']??'')==='http'&&in_array($host,['localhost','127.0.0.1'],true);if($host===''||(($parts['scheme']??'')!=='https'&&!$loopback)||isset($parts['user'])||isset($parts['pass'])||isset($parts['query'])||isset($parts['fragment'])||(isset($parts['path'])&&!in_array($parts['path'],['','/'],true)))throw new \InvalidArgumentException('base URL must be an HTTPS origin');}
}

final class CheckoutClient {
    public function __construct(private readonly string $baseUrl,private readonly float $timeoutSeconds=10.0){Client::validateBaseUrl($baseUrl);}
    public function getSession(string $token): CheckoutSession {
        if(!preg_match('/^cs_[A-Za-z0-9_-]{43}$/',$token))throw new \InvalidArgumentException('invalid checkout token');
        $context=stream_context_create(['http'=>['method'=>'GET','header'=>'Accept: application/json','timeout'=>$this->timeoutSeconds,'ignore_errors'=>true,'follow_location'=>0,'max_redirects'=>0]]);$raw=@file_get_contents(rtrim($this->baseUrl,'/').'/v1/checkout-sessions/'.rawurlencode($token),false,$context);$status=0;foreach($http_response_header??[]as$line)if(preg_match('/^HTTP\/\S+\s+(\d+)/',$line,$match))$status=(int)$match[1];
        if($raw===false||$status!==200)throw new MerchantApiException($status,'checkout_unavailable','checkout session unavailable',retryable:$status===429||$status>=500);
        try{$value=json_decode($raw,true,512,JSON_THROW_ON_ERROR);}catch(\JsonException){throw new MerchantApiException(200,'invalid_response','invalid checkout response');}$statuses=['pending','detected','confirming','settled','expired','preparing_payment_route','payment_route_failed'];if(!in_array($value['status']??'', $statuses,true)||!is_array($value['routes']??null)||!is_string($value['selected_route_id']??null))throw new MerchantApiException(200,'invalid_response','invalid checkout response');$waiting=in_array($value['status'],['preparing_payment_route','payment_route_failed'],true);if(($waiting&&($value['routes']!==[]||$value['selected_route_id']!==''))||(!$waiting&&$value['routes']===[]))throw new MerchantApiException(200,'invalid_response','invalid checkout response');
        $routes=[];foreach($value['routes']as$route){$provider=$route['provider']??'';$onChain=$provider==='on_chain'&&isset($route['network'],$route['address'])&&!isset($route['payment_url']);$hosted=$provider==='hosted_gateway'&&isset($route['provider_id'],$route['payment_url'])&&!isset($route['network'],$route['address'])&&str_starts_with((string)$route['payment_url'],'https://');if(!isset($route['id'],$route['asset'],$route['amount'])||(!$onChain&&!$hosted)||!preg_match('/^\d+(\.\d+)?$/',(string)$route['amount']))throw new MerchantApiException(200,'invalid_response','invalid checkout route');$routes[]=new CheckoutRoute((string)$route['id'],$provider,(string)$route['asset'],(string)$route['amount'],$onChain?(string)$route['network']:null,$onChain?(string)$route['address']:null,$hosted?(string)$route['provider_id']:null,$hosted?(string)$route['payment_url']:null,isset($route['transaction_hash'])?(string)$route['transaction_hash']:null,isset($route['explorer_url'])?(string)$route['explorer_url']:null);}
        if($value['selected_route_id']!==''&&!array_filter($routes,static fn($route)=>$route->id===$value['selected_route_id']))throw new MerchantApiException(200,'invalid_response','invalid selected checkout route');return new CheckoutSession($value['intent_id'],$value['order_id'],$value['status'],$value['expires_at'],$value['selected_route_id'],$routes);
    }
    public function getPaymentLink(string $token): array{return $this->publicRequest('GET','/v1/public/payment-links/'.rawurlencode($this->token($token,'pl')));}
    public function redeemPaymentLink(string $token,string $key,array $value=[],?string $origin=null): array{return $this->publicRequest('POST','/v1/public/payment-links/'.rawurlencode($this->token($token,'pl')).'/redeem',$value,$key,$origin);}
    public function selectRoute(string $token,string $routeId,string $key,?string $origin=null): array{return $this->publicRequest('POST','/v1/checkout-sessions/'.rawurlencode($this->token($token,'cs')).'/select-route',['route_id'=>$routeId],$key,$origin);}
    private function token(string $value,string $prefix): string{if(!preg_match('/^'.preg_quote($prefix,'/').'_[A-Za-z0-9_-]{43}$/',$value))throw new \InvalidArgumentException('invalid capability token');return $value;}
    private function publicRequest(string $method,string $path,?array $value=null,?string $key=null,?string $origin=null): array{$body=$value===null?null:json_encode($value,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$headers=['Accept: application/json'];if($body!==null)$headers[]='Content-Type: application/json';if($key!==null)$headers[]='Idempotency-Key: '.$key;if($origin!==null)$headers[]='Origin: '.$origin;$context=stream_context_create(['http'=>['method'=>$method,'header'=>implode("\r\n",$headers),'content'=>$body??'','timeout'=>$this->timeoutSeconds,'ignore_errors'=>true,'follow_location'=>0,'max_redirects'=>0]]);$raw=@file_get_contents(rtrim($this->baseUrl,'/').$path,false,$context);$status=0;foreach($http_response_header??[]as$line)if(preg_match('/^HTTP\/\S+\s+(\d+)/',$line,$match))$status=(int)$match[1];if($raw===false||$status<200||$status>=300)throw new MerchantApiException($status,'checkout_unavailable','public checkout request failed',retryable:$status===429||$status>=500);return json_decode($raw,true,512,JSON_THROW_ON_ERROR);}
}
