<?php
declare(strict_types=1);
namespace MerchantPlatform;

final class EndpointConfig {private function __construct(public readonly string $environment,public readonly string $baseUrl){}public static function live(string $url):self{return new self('live',$url);}public static function sandbox(string $url):self{return new self('sandbox',$url);}}
final class RetryPolicy {public function __construct(public readonly int $maxAttempts=4,public readonly float $baseDelay=0.2,public readonly float $maxDelay=5.0,public readonly float $jitterRatio=0.2){if($maxAttempts<1||$maxAttempts>10)throw new \InvalidArgumentException('maxAttempts must be 1..10');}}
final class Integration {
    /** The caller must opt in. Unsafe operations need the same non-empty idempotency key on every attempt. */
    public static function withRetry(callable $action,bool $safe,?string $idempotencyKey=null,?RetryPolicy $policy=null): mixed{$policy??=new RetryPolicy();if(!$safe&&($idempotencyKey===null||$idempotencyKey===''))throw new \InvalidArgumentException('unsafe retries require an idempotency key');for($attempt=1;;$attempt++){try{return $action();}catch(MerchantApiException $error){if(!$error->retryable||$attempt>=$policy->maxAttempts)throw $error;$delay=min($policy->maxDelay,$policy->baseDelay*(2**($attempt-1)));if($error->retryAfterSeconds!==null){$delay=min($policy->maxDelay,$error->retryAfterSeconds);}else{$delay*=1+(((random_int(0,1000000)/1000000)*2-1)*$policy->jitterRatio);}usleep((int)(max(0,$delay)*1000000));}}}
    /** OpenTelemetry-style hook: emits bounded fields, never URL, body, IDs, headers, or secrets. */
    public static function instrument(string $operation,string $method,?callable $hook,callable $action):mixed{if(!preg_match('/^[a-z][a-z0-9_.-]{0,63}$/',$operation)||!preg_match('/^[A-Z]{3,7}$/',$method))throw new \InvalidArgumentException('telemetry operation or method is not low-cardinality');$started=hrtime(true);$hook&&$hook(['phase'=>'start','operation'=>$operation,'method'=>$method]);try{$value=$action();$hook&&$hook(['phase'=>'end','operation'=>$operation,'method'=>$method,'status'=>200,'duration_ms'=>(int)((hrtime(true)-$started)/1000000)]);return$value;}catch(\Throwable$error){$hook&&$hook(['phase'=>'end','operation'=>$operation,'method'=>$method,'status'=>$error instanceof MerchantApiException?$error->status:0,'duration_ms'=>(int)((hrtime(true)-$started)/1000000),'retryable'=>$error instanceof MerchantApiException&&$error->retryable]);throw$error;}}
    public static function paymentIntents(Client $client,?string $status=null,int $pageSize=100):\Generator{$after=null;do{$page=$client->listPaymentIntents($status,$after,$pageSize)->data;foreach($page->items as$item)yield$item;$next=$page->nextCursor;$after=$next!==''?$next:null;}while($after!==null);}
    public static function events(Client $client,int $afterSequence=0,int $pageSize=100):\Generator{$cursor=$afterSequence;for(;;){$page=$client->listEvents($cursor,$pageSize)->data;foreach($page->items as$item)yield$item;if($page->items===[]||$page->nextSequence===(string)$cursor)return;$cursor=(int)$page->nextSequence;}}
}
