package com.merchantplatform;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.SerializationFeature;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class MerchantClient {
    private final String baseUrl,keyId,secret;private final Duration timeout;private final HttpClient http;private final ObjectMapper json;private final int maxReportBytes=268435456;
    public MerchantClient(String baseUrl,String keyId,String secret,Duration timeout){validateBaseUrl(baseUrl);this.baseUrl=baseUrl.replaceAll("/$","");this.keyId=keyId;this.secret=secret;this.timeout=timeout==null?Duration.ofSeconds(10):timeout;this.http=HttpClient.newBuilder().connectTimeout(this.timeout).followRedirects(HttpClient.Redirect.NEVER).build();this.json=new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE).setSerializationInclusion(JsonInclude.Include.NON_NULL).disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);}
    public Models.Envelope<Models.PaymentIntent> createPaymentIntent(Models.CreatePaymentIntentRequest value,String key)throws ApiException{return envelope(request("POST","/v1/payment-intents",value,Map.of(),key),Models.PaymentIntent.class);}
    public Models.Envelope<Models.CursorPage<Models.PaymentIntent>> listPaymentIntents(String status,String after,int limit)throws ApiException{Map<String,List<?>> query=new LinkedHashMap<>();if(status!=null)query.put("status",List.of(status));if(after!=null)query.put("after",List.of(after));query.put("limit",List.of(limit));JsonNode root=request("GET","/v1/payment-intents",null,query,null);List<Models.PaymentIntent> items=json.convertValue(root.path("data").path("items"),new TypeReference<List<Models.PaymentIntent>>(){});return new Models.Envelope<>(new Models.CursorPage<>(items,root.path("data").path("next_cursor").asText("")),root.path("request_id").asText(),root.path("api_version").asText());}
    public Models.Envelope<Models.PaymentIntent> getPaymentIntent(String id)throws ApiException{return envelope(request("GET","/v1/payment-intents/"+Signing.pathSegment(id),null,Map.of(),null),Models.PaymentIntent.class);}
    public Models.Envelope<Models.PaymentRoute> createPaymentRoute(String intentId,Models.CreatePaymentRouteRequest value,String key)throws ApiException{return envelope(request("POST","/v1/payment-intents/"+Signing.pathSegment(intentId)+"/routes",value,Map.of(),key),Models.PaymentRoute.class);}
    public Models.Envelope<List<Models.PaymentRoute>> listPaymentRoutes(String intentId)throws ApiException{JsonNode root=request("GET","/v1/payment-intents/"+Signing.pathSegment(intentId)+"/routes",null,Map.of(),null);List<Models.PaymentRoute> items=json.convertValue(root.path("data").path("items"),new TypeReference<List<Models.PaymentRoute>>(){});return new Models.Envelope<>(items,root.path("request_id").asText(),root.path("api_version").asText());}
    public Models.Envelope<Models.PaymentIntent> cancelPaymentIntent(String intentId,Models.CancelPaymentIntentRequest value,String key)throws ApiException{return envelope(request("POST","/v1/payment-intents/"+Signing.pathSegment(intentId)+"/cancel",value,Map.of(),key),Models.PaymentIntent.class);}
    public Models.Envelope<Models.PaymentIntent> expirePaymentIntent(String intentId,Models.ExpirePaymentIntentRequest value,String key)throws ApiException{return envelope(request("POST","/v1/payment-intents/"+Signing.pathSegment(intentId)+"/expire",value,Map.of(),key),Models.PaymentIntent.class);}
    public Models.Envelope<Models.PaymentIntent> updatePaymentIntentMetadata(String intentId,Models.UpdatePaymentIntentMetadataRequest value,String key)throws ApiException{return envelope(request("POST","/v1/payment-intents/"+Signing.pathSegment(intentId)+"/metadata",value,Map.of(),key),Models.PaymentIntent.class);}
    public Models.Envelope<List<Models.Asset>> listAssets()throws ApiException{JsonNode root=request("GET","/v1/assets",null,Map.of(),null);List<Models.Asset> items=json.convertValue(root.path("data").path("items"),new TypeReference<List<Models.Asset>>(){});return new Models.Envelope<>(items,root.path("request_id").asText(),root.path("api_version").asText());}
    public Models.Envelope<Models.PaymentProof> submitPaymentProof(Models.SubmitPaymentProofRequest value,String key)throws ApiException{return envelope(request("POST","/v1/payment-proofs",value,Map.of(),key),Models.PaymentProof.class);}
    public Models.Envelope<Models.PaymentProof> getPaymentProof(String id)throws ApiException{return envelope(request("GET","/v1/payment-proofs/"+Signing.pathSegment(id),null,Map.of(),null),Models.PaymentProof.class);}
    public Models.Envelope<Models.EventPage<Models.PublicEvent>> listEvents(long afterSequence,int limit)throws ApiException{Map<String,List<?>>query=new LinkedHashMap<>();query.put("after_sequence",List.of(afterSequence));query.put("limit",List.of(limit));JsonNode root=request("GET","/v1/events",null,query,null);List<Models.PublicEvent>items=json.convertValue(root.path("data").path("items"),new TypeReference<List<Models.PublicEvent>>(){});return new Models.Envelope<>(new Models.EventPage<>(items,root.path("data").path("next_cursor").asText(),root.path("data").path("next_sequence").asText()),root.path("request_id").asText(),root.path("api_version").asText());}
    public Models.Envelope<JsonNode> getEvent(String id)throws ApiException{return nodeEnvelope(request("GET","/v1/events/"+Signing.pathSegment(id),null,Map.of(),null));}
    public Models.Envelope<JsonNode> listTransfers(String after,int limit)throws ApiException{return nodeEnvelope(request("GET","/v1/transfers",null,pageQuery(after,limit),null));}
    public Models.Envelope<JsonNode> getTransferEvents(String network,String transactionId)throws ApiException{return nodeEnvelope(request("GET","/v1/transfers/"+Signing.pathSegment(network)+"/"+Signing.pathSegment(transactionId),null,Map.of(),null));}
    public Models.Envelope<JsonNode> listQuotes(String after,int limit)throws ApiException{return nodeEnvelope(request("GET","/v1/quotes",null,pageQuery(after,limit),null));}
    public Models.Envelope<JsonNode> getQuote(String id)throws ApiException{return nodeEnvelope(request("GET","/v1/quotes/"+Signing.pathSegment(id),null,Map.of(),null));}
    public Models.Envelope<JsonNode> listBalances()throws ApiException{return nodeEnvelope(request("GET","/v1/balances",null,Map.of(),null));}
    public Models.Envelope<JsonNode> getReconciliation()throws ApiException{return nodeEnvelope(request("GET","/v1/reconciliation",null,Map.of(),null));}
    public Models.Envelope<Models.ReconciliationReport> createReconciliationReport(Models.CreateReconciliationReportRequest value,String key)throws ApiException{return envelope(request("POST","/v1/reconciliation-reports",value,Map.of(),key),Models.ReconciliationReport.class);}
    public Models.Envelope<Models.ReconciliationReport> getReconciliationReport(String id)throws ApiException{return envelope(request("GET","/v1/reconciliation-reports/"+Signing.pathSegment(id),null,Map.of(),null),Models.ReconciliationReport.class);}
    public JsonNode createPaymentLink(Object value,String key)throws ApiException{return request("POST","/v1/payment-links",value,Map.of(),key);}
    public JsonNode listPaymentLinks(String cursor,int limit)throws ApiException{Map<String,List<?>>query=new LinkedHashMap<>();if(cursor!=null)query.put("cursor",List.of(cursor));query.put("limit",List.of(limit));return request("GET","/v1/payment-links",null,query,null);}
    public JsonNode getPaymentLink(String id)throws ApiException{return request("GET","/v1/payment-links/"+Signing.pathSegment(id),null,Map.of(),null);}
    public JsonNode disablePaymentLink(String id,long version,String key)throws ApiException{return request("POST","/v1/payment-links/"+Signing.pathSegment(id)+"/disable",Map.of("version",version),Map.of(),key);}
    public JsonNode createCheckoutSession(Object value,String key)throws ApiException{return request("POST","/v1/checkout-sessions",value,Map.of(),key);}
    public Models.ReportDownload downloadReconciliationReport(String id)throws ApiException{String path="/v1/reconciliation-reports/"+Signing.pathSegment(id)+"/download";try{Signing.SignedHeaders signed=Signing.signRequest(keyId,secret,"GET",path,new byte[0],Instant.now().getEpochSecond(),Signing.randomNonce());HttpRequest.Builder builder=HttpRequest.newBuilder(URI.create(baseUrl+path)).timeout(Duration.ofMinutes(15)).header("Accept","application/x-ndjson").GET();signed.asMap().forEach(builder::header);HttpResponse<java.io.InputStream>response=http.send(builder.build(),HttpResponse.BodyHandlers.ofInputStream());if(response.statusCode()!=200){response.body().close();throw new ApiException(response.statusCode(),"report_unavailable","reconciliation report unavailable",null,null,response.statusCode()==429||response.statusCode()>=500);}String digest=response.headers().firstValue("X-Reconciliation-SHA256").orElse(""),signature=response.headers().firstValue("X-Reconciliation-Signature").orElse(""),key=response.headers().firstValue("X-Reconciliation-Signing-Key-Id").orElse("");byte[]raw;try(var stream=response.body()){raw=stream.readNBytes(maxReportBytes+1);}if(raw.length>maxReportBytes)throw new ApiException(200,"report_too_large","reconciliation report exceeds configured client limit",null,null,false);if(!digest.matches("^[0-9a-f]{64}$")||signature.isEmpty()||key.isEmpty())throw new ApiException(200,"invalid_response","missing reconciliation integrity headers",null,null,false);return new Models.ReportDownload(raw,digest,signature,key);}catch(ApiException error){throw error;}catch(Exception error){throw new ApiException(0,"transport_error","report download failed",null,null,true);}}
    private Map<String,List<?>>pageQuery(String after,int limit){Map<String,List<?>>query=new LinkedHashMap<>();if(after!=null)query.put("after",List.of(after));query.put("limit",List.of(limit));return query;}
    private JsonNode request(String method,String path,Object payload,Map<String,? extends List<?>> query,String idempotencyKey)throws ApiException{if(idempotencyKey!=null&&(idempotencyKey.length()<8||idempotencyKey.length()>255))throw new IllegalArgumentException("idempotency key must be 8..255 characters");try{String encoded=Signing.canonicalQuery(query),pathAndQuery=path+(encoded.isEmpty()?"":"?"+encoded);byte[]body=payload==null?new byte[0]:json.writeValueAsBytes(payload);Signing.SignedHeaders signed=Signing.signRequest(keyId,secret,method,pathAndQuery,body,Instant.now().getEpochSecond(),Signing.randomNonce());HttpRequest.Builder builder=HttpRequest.newBuilder(URI.create(baseUrl+pathAndQuery)).timeout(timeout).header("Accept","application/json");signed.asMap().forEach(builder::header);if(idempotencyKey!=null)builder.header("Idempotency-Key",idempotencyKey);if(payload!=null)builder.header("Content-Type","application/json");builder.method(method,payload==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofByteArray(body));HttpResponse<byte[]>response=http.send(builder.build(),HttpResponse.BodyHandlers.ofByteArray());JsonNode root=response.body().length==0?json.createObjectNode():json.readTree(response.body());if(response.statusCode()<200||response.statusCode()>=300){JsonNode error=root.path("error");throw new ApiException(response.statusCode(),error.path("code").asText("http_error"),error.path("message").asText("API request failed"),root.path("request_id").asText(null),json.convertValue(error.path("details"),new TypeReference<Map<String,Object>>(){}),response.statusCode()==429||response.statusCode()>=500,retryAfter(response.headers().firstValue("Retry-After").orElse(null)));}return root;}catch(ApiException error){throw error;}catch(java.net.http.HttpTimeoutException error){throw new ApiException(0,"timeout","request timed out",null,null,true);}catch(Exception error){throw new ApiException(0,"transport_error","request failed",null,null,true);}}
    private <T>Models.Envelope<T> envelope(JsonNode root,Class<T> type)throws ApiException{try{return new Models.Envelope<>(json.treeToValue(root.path("data"),type),root.path("request_id").asText(),root.path("api_version").asText());}catch(Exception error){throw new ApiException(200,"invalid_response","invalid API response",root.path("request_id").asText(null),null,false);}}
    private Models.Envelope<JsonNode> nodeEnvelope(JsonNode root){return new Models.Envelope<>(root.path("data"),root.path("request_id").asText(),root.path("api_version").asText());}
    static void validateBaseUrl(String value){URI uri=URI.create(value);String host=uri.getHost();boolean loopback="http".equals(uri.getScheme())&&("localhost".equals(host)||"127.0.0.1".equals(host));if(host==null||(!"https".equals(uri.getScheme())&&!loopback)||uri.getUserInfo()!=null||uri.getRawQuery()!=null||uri.getFragment()!=null||(uri.getPath()!=null&&!uri.getPath().isEmpty()&&!"/".equals(uri.getPath())))throw new IllegalArgumentException("base URL must be an HTTPS origin");}
    private static long retryAfter(String value){try{return value==null?0:Math.min(300,Math.max(0,Long.parseLong(value)));}catch(NumberFormatException ignored){return 0;}}
    public static final class ApiException extends Exception{public final int status;public final String code,requestId;public final Map<String,Object>details;public final boolean retryable;public final long retryAfterSeconds;public ApiException(int status,String code,String message,String requestId,Map<String,Object>details,boolean retryable){this(status,code,message,requestId,details,retryable,0);}public ApiException(int status,String code,String message,String requestId,Map<String,Object>details,boolean retryable,long retryAfterSeconds){super(message);this.status=status;this.code=code;this.requestId=requestId;this.details=details;this.retryable=retryable;this.retryAfterSeconds=retryAfterSeconds;}@Override public String toString(){return "MerchantApiException{status="+status+", code='"+code+"', requestId='"+requestId+"'}";}}
}
