using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace MerchantPlatform;

public sealed record EndpointConfig(string Environment,string BaseUrl){public static EndpointConfig Live(string url)=>new("live",url);public static EndpointConfig Sandbox(string url)=>new("sandbox",url);}
public sealed record RetryPolicy(int MaxAttempts=4,TimeSpan BaseDelay=default,TimeSpan MaxDelay=default,double JitterRatio=0.2){public TimeSpan EffectiveBase=>BaseDelay==default?TimeSpan.FromMilliseconds(200):BaseDelay;public TimeSpan EffectiveMax=>MaxDelay==default?TimeSpan.FromSeconds(5):MaxDelay;}
public sealed record TelemetryEvent(string Phase,string Operation,string Method,int Status=0,long DurationMs=0,bool Retryable=false);
public static class Integration {
    public static async Task<T> WithRetryAsync<T>(Func<Task<T>> action,bool safe,string? idempotencyKey=null,RetryPolicy? policy=null,CancellationToken token=default){policy??=new();if(!safe&&string.IsNullOrEmpty(idempotencyKey))throw new ArgumentException("unsafe retries require an idempotency key");if(policy.MaxAttempts<1||policy.MaxAttempts>10)throw new ArgumentException("MaxAttempts must be 1..10");for(var attempt=1;;attempt++){try{return await action();}catch(MerchantApiException error)when(error.Retryable&&attempt<policy.MaxAttempts){var exponential=TimeSpan.FromMilliseconds(Math.Min(policy.EffectiveMax.TotalMilliseconds,policy.EffectiveBase.TotalMilliseconds*Math.Pow(2,attempt-1)));TimeSpan delay;if(error.RetryAfter is not null){delay=error.RetryAfter.Value<policy.EffectiveMax?error.RetryAfter.Value:policy.EffectiveMax;}else{delay=TimeSpan.FromMilliseconds(Math.Max(0,Math.Min(policy.EffectiveMax.TotalMilliseconds,exponential.TotalMilliseconds*(1+(Random.Shared.NextDouble()*2-1)*policy.JitterRatio))));}await Task.Delay(delay,token);}}}
    public static async Task<T> InstrumentAsync<T>(string operation,string method,Action<TelemetryEvent>? hook,Func<Task<T>> action){if(!System.Text.RegularExpressions.Regex.IsMatch(operation,"^[a-z][a-z0-9_.-]{0,63}$")||!System.Text.RegularExpressions.Regex.IsMatch(method,"^[A-Z]{3,7}$"))throw new ArgumentException("telemetry operation or method is not low-cardinality");var watch=Stopwatch.StartNew();hook?.Invoke(new("start",operation,method));try{var value=await action();hook?.Invoke(new("end",operation,method,200,watch.ElapsedMilliseconds));return value;}catch(MerchantApiException error){hook?.Invoke(new("end",operation,method,error.Status,watch.ElapsedMilliseconds,error.Retryable));throw;}}
    public static async IAsyncEnumerable<PaymentIntent> PaymentIntentsAsync(MerchantClient client,string? status=null,int pageSize=100,[EnumeratorCancellation]CancellationToken token=default){string? after=null;do{var page=await client.ListPaymentIntentsAsync(status,after,pageSize,token);foreach(var item in page.Data.Items)yield return item;after=string.IsNullOrEmpty(page.Data.NextCursor)?null:page.Data.NextCursor;}while(after is not null);}
    public static async IAsyncEnumerable<PublicEvent> EventsAsync(MerchantClient client,long afterSequence=0,int pageSize=100,[EnumeratorCancellation]CancellationToken token=default){var cursor=afterSequence;for(;;){var page=await client.ListEventsAsync(cursor,pageSize,token);foreach(var item in page.Data.Items)yield return item;if(page.Data.Items.Count==0||page.Data.NextSequence==cursor.ToString(System.Globalization.CultureInfo.InvariantCulture))yield break;cursor=long.Parse(page.Data.NextSequence,System.Globalization.CultureInfo.InvariantCulture);}}
}
