using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;

namespace MerchantPlatform;

public sealed class MerchantApiException(int status,string code,string message,string? requestId=null,IReadOnlyDictionary<string,object?>? details=null,bool retryable=false,TimeSpan? retryAfter=null):Exception(message){public int Status{get;}=status;public string Code{get;}=code;public string? RequestId{get;}=requestId;public IReadOnlyDictionary<string,object?>? Details{get;}=details;public bool Retryable{get;}=retryable;public TimeSpan? RetryAfter{get;}=retryAfter;public override string ToString()=>$"MerchantApiException(Status={Status}, Code={Code}, RequestId={RequestId})";}
public sealed class MerchantClient {
    private const int MaxReportBytes=268435456;
    private readonly string _baseUrl,_keyId,_secret;private readonly HttpClient _http;private readonly JsonSerializerOptions _json=new(){PropertyNamingPolicy=JsonNamingPolicy.SnakeCaseLower,PropertyNameCaseInsensitive=true,DefaultIgnoreCondition=System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull};
    public MerchantClient(string baseUrl,string keyId,string secret,TimeSpan? timeout=null,HttpMessageHandler? handler=null){ValidateBaseUrl(baseUrl);_baseUrl=baseUrl.TrimEnd('/');_keyId=keyId;_secret=secret;_http=handler is null?new HttpClient(new HttpClientHandler{AllowAutoRedirect=false}):new HttpClient(handler);_http.Timeout=timeout??TimeSpan.FromSeconds(10);}
    public async Task<Envelope<PaymentIntent>> CreatePaymentIntentAsync(CreatePaymentIntentRequest value,string key,CancellationToken cancellationToken=default){value.Validate();return await EnvelopeAsync<PaymentIntent>(await RequestAsync(HttpMethod.Post,"/v1/payment-intents",value,null,key,cancellationToken));}
    public async Task<Envelope<CursorPage<PaymentIntent>>> ListPaymentIntentsAsync(string? status=null,string? after=null,int limit=50,CancellationToken cancellationToken=default){var query=Query(("status",status),("after",after),("limit",limit));var root=await RequestAsync(HttpMethod.Get,"/v1/payment-intents",null,query,null,cancellationToken);var data=root.GetProperty("data");return new(new(data.GetProperty("items").Deserialize<List<PaymentIntent>>(_json)!,data.TryGetProperty("next_cursor",out var next)?next.GetString()??"":""),root.GetProperty("request_id").GetString()!,root.GetProperty("api_version").GetString()!);}
    public async Task<Envelope<PaymentIntent>> GetPaymentIntentAsync(string id,CancellationToken cancellationToken=default)=>await EnvelopeAsync<PaymentIntent>(await RequestAsync(HttpMethod.Get,"/v1/payment-intents/"+Signing.PathSegment(id),null,null,null,cancellationToken));
    public async Task<Envelope<PaymentRoute>> CreatePaymentRouteAsync(string intentId,CreatePaymentRouteRequest value,string key,CancellationToken cancellationToken=default)=>await EnvelopeAsync<PaymentRoute>(await RequestAsync(HttpMethod.Post,"/v1/payment-intents/"+Signing.PathSegment(intentId)+"/routes",value,null,key,cancellationToken));
    public async Task<Envelope<IReadOnlyList<PaymentRoute>>> ListPaymentRoutesAsync(string intentId,CancellationToken cancellationToken=default){var root=await RequestAsync(HttpMethod.Get,"/v1/payment-intents/"+Signing.PathSegment(intentId)+"/routes",null,null,null,cancellationToken);return new(root.GetProperty("data").GetProperty("items").Deserialize<List<PaymentRoute>>(_json)!,root.GetProperty("request_id").GetString()!,root.GetProperty("api_version").GetString()!);}
    public async Task<Envelope<PaymentIntent>> CancelPaymentIntentAsync(string intentId,CancelPaymentIntentRequest value,string key,CancellationToken cancellationToken=default)=>await EnvelopeAsync<PaymentIntent>(await RequestAsync(HttpMethod.Post,"/v1/payment-intents/"+Signing.PathSegment(intentId)+"/cancel",value,null,key,cancellationToken));
    public async Task<Envelope<PaymentIntent>> ExpirePaymentIntentAsync(string intentId,ExpirePaymentIntentRequest value,string key,CancellationToken cancellationToken=default)=>await EnvelopeAsync<PaymentIntent>(await RequestAsync(HttpMethod.Post,"/v1/payment-intents/"+Signing.PathSegment(intentId)+"/expire",value,null,key,cancellationToken));
    public async Task<Envelope<PaymentIntent>> UpdatePaymentIntentMetadataAsync(string intentId,UpdatePaymentIntentMetadataRequest value,string key,CancellationToken cancellationToken=default)=>await EnvelopeAsync<PaymentIntent>(await RequestAsync(HttpMethod.Post,"/v1/payment-intents/"+Signing.PathSegment(intentId)+"/metadata",value,null,key,cancellationToken));
    public async Task<Envelope<IReadOnlyList<Asset>>> ListAssetsAsync(CancellationToken cancellationToken=default){var root=await RequestAsync(HttpMethod.Get,"/v1/assets",null,null,null,cancellationToken);return new(root.GetProperty("data").GetProperty("items").Deserialize<List<Asset>>(_json)!,root.GetProperty("request_id").GetString()!,root.GetProperty("api_version").GetString()!);}
    public async Task<Envelope<PaymentProof>> SubmitPaymentProofAsync(SubmitPaymentProofRequest value,string key,CancellationToken cancellationToken=default)=>await EnvelopeAsync<PaymentProof>(await RequestAsync(HttpMethod.Post,"/v1/payment-proofs",value,null,key,cancellationToken));
    public async Task<Envelope<PaymentProof>> GetPaymentProofAsync(string id,CancellationToken cancellationToken=default)=>await EnvelopeAsync<PaymentProof>(await RequestAsync(HttpMethod.Get,"/v1/payment-proofs/"+Signing.PathSegment(id),null,null,null,cancellationToken));
    public async Task<Envelope<EventPage<PublicEvent>>> ListEventsAsync(long afterSequence=0,int limit=100,CancellationToken cancellationToken=default){var root=await RequestAsync(HttpMethod.Get,"/v1/events",null,Query(("after_sequence",afterSequence),("limit",limit)),null,cancellationToken);var data=root.GetProperty("data");return new(new(data.GetProperty("items").Deserialize<List<PublicEvent>>(_json)!,data.GetProperty("next_cursor").GetString()!,data.GetProperty("next_sequence").GetString()!),root.GetProperty("request_id").GetString()!,root.GetProperty("api_version").GetString()!);}
    public async Task<Envelope<JsonElement>> GetEventAsync(string id,CancellationToken token=default)=>await NodeEnvelopeAsync(await RequestAsync(HttpMethod.Get,"/v1/events/"+Signing.PathSegment(id),null,null,null,token));
    public async Task<Envelope<JsonElement>> ListTransfersAsync(string? after=null,int limit=50,CancellationToken token=default)=>await NodeEnvelopeAsync(await RequestAsync(HttpMethod.Get,"/v1/transfers",null,Query(("after",after),("limit",limit)),null,token));
    public async Task<Envelope<JsonElement>> GetTransferEventsAsync(string network,string transactionId,CancellationToken token=default)=>await NodeEnvelopeAsync(await RequestAsync(HttpMethod.Get,"/v1/transfers/"+Signing.PathSegment(network)+"/"+Signing.PathSegment(transactionId),null,null,null,token));
    public async Task<Envelope<JsonElement>> ListQuotesAsync(string? after=null,int limit=50,CancellationToken token=default)=>await NodeEnvelopeAsync(await RequestAsync(HttpMethod.Get,"/v1/quotes",null,Query(("after",after),("limit",limit)),null,token));
    public async Task<Envelope<JsonElement>> GetQuoteAsync(string id,CancellationToken token=default)=>await NodeEnvelopeAsync(await RequestAsync(HttpMethod.Get,"/v1/quotes/"+Signing.PathSegment(id),null,null,null,token));
    public async Task<Envelope<JsonElement>> ListBalancesAsync(CancellationToken token=default)=>await NodeEnvelopeAsync(await RequestAsync(HttpMethod.Get,"/v1/balances",null,null,null,token));
    public async Task<Envelope<JsonElement>> GetReconciliationAsync(CancellationToken token=default)=>await NodeEnvelopeAsync(await RequestAsync(HttpMethod.Get,"/v1/reconciliation",null,null,null,token));
    public async Task<Envelope<ReconciliationReport>> CreateReconciliationReportAsync(CreateReconciliationReportRequest value,string key,CancellationToken token=default)=>await EnvelopeAsync<ReconciliationReport>(await RequestAsync(HttpMethod.Post,"/v1/reconciliation-reports",value,null,key,token));
    public async Task<Envelope<ReconciliationReport>> GetReconciliationReportAsync(string id,CancellationToken token=default)=>await EnvelopeAsync<ReconciliationReport>(await RequestAsync(HttpMethod.Get,"/v1/reconciliation-reports/"+Signing.PathSegment(id),null,null,null,token));
    public async Task<JsonElement> CreatePaymentLinkAsync(object value,string key,CancellationToken token=default)=>await RequestAsync(HttpMethod.Post,"/v1/payment-links",value,null,key,token);
    public async Task<JsonElement> ListPaymentLinksAsync(string? cursor=null,int limit=50,CancellationToken token=default)=>await RequestAsync(HttpMethod.Get,"/v1/payment-links",null,Query(("cursor",cursor),("limit",limit)),null,token);
    public async Task<JsonElement> GetPaymentLinkAsync(string id,CancellationToken token=default)=>await RequestAsync(HttpMethod.Get,"/v1/payment-links/"+Signing.PathSegment(id),null,null,null,token);
    public async Task<JsonElement> DisablePaymentLinkAsync(string id,long version,string key,CancellationToken token=default)=>await RequestAsync(HttpMethod.Post,"/v1/payment-links/"+Signing.PathSegment(id)+"/disable",new{version},null,key,token);
    public async Task<JsonElement> CreateCheckoutSessionAsync(object value,string key,CancellationToken token=default)=>await RequestAsync(HttpMethod.Post,"/v1/checkout-sessions",value,null,key,token);
    public async Task<ReportDownload> DownloadReconciliationReportAsync(string id,CancellationToken token=default){var path="/v1/reconciliation-reports/"+Signing.PathSegment(id)+"/download";var signed=Signing.SignRequest(_keyId,_secret,"GET",path,Array.Empty<byte>(),DateTimeOffset.UtcNow.ToUnixTimeSeconds(),Signing.RandomNonce());using var request=new HttpRequestMessage(HttpMethod.Get,_baseUrl+path);foreach(var header in signed.AsDictionary())request.Headers.TryAddWithoutValidation(header.Key,header.Value);request.Headers.Accept.ParseAdd("application/x-ndjson");using var response=await _http.SendAsync(request,HttpCompletionOption.ResponseHeadersRead,token);if(!response.IsSuccessStatusCode)throw new MerchantApiException((int)response.StatusCode,"report_unavailable","reconciliation report unavailable",retryable:response.StatusCode==HttpStatusCode.TooManyRequests||(int)response.StatusCode>=500);await using var source=await response.Content.ReadAsStreamAsync(token);using var output=new MemoryStream();var buffer=new byte[81920];for(;;){var count=await source.ReadAsync(buffer,token);if(count==0)break;if(output.Length+count>MaxReportBytes)throw new MerchantApiException(200,"report_too_large","reconciliation report exceeds configured client limit");await output.WriteAsync(buffer.AsMemory(0,count),token);}var bytes=output.ToArray();string Header(string name)=>response.Headers.TryGetValues(name,out var values)?values.FirstOrDefault()??"":"";var digest=Header("X-Reconciliation-SHA256");var signature=Header("X-Reconciliation-Signature");var signingKeyId=Header("X-Reconciliation-Signing-Key-Id");if(!System.Text.RegularExpressions.Regex.IsMatch(digest,"^[0-9a-f]{64}$")||signature.Length==0||signingKeyId.Length==0)throw new MerchantApiException(200,"invalid_response","missing reconciliation integrity headers");return new(bytes,digest,signature,signingKeyId);}
    private async Task<JsonElement> RequestAsync(HttpMethod method,string path,object? payload,IReadOnlyDictionary<string,IReadOnlyList<object?>>? query,string? idempotencyKey,CancellationToken cancellationToken){if(idempotencyKey is not null&&(idempotencyKey.Length<8||idempotencyKey.Length>255))throw new ArgumentException("idempotency key must be 8..255 characters");var encoded=query is null?"":Signing.CanonicalQuery(query);var pathAndQuery=path+(encoded.Length>0?"?"+encoded:"");var body=payload is null?Array.Empty<byte>():JsonSerializer.SerializeToUtf8Bytes(payload,_json);var signed=Signing.SignRequest(_keyId,_secret,method.Method,pathAndQuery,body,DateTimeOffset.UtcNow.ToUnixTimeSeconds(),Signing.RandomNonce());using var request=new HttpRequestMessage(method,_baseUrl+pathAndQuery);foreach(var header in signed.AsDictionary())request.Headers.TryAddWithoutValidation(header.Key,header.Value);request.Headers.Accept.ParseAdd("application/json");if(idempotencyKey is not null)request.Headers.TryAddWithoutValidation("Idempotency-Key",idempotencyKey);if(payload is not null)request.Content=new ByteArrayContent(body){Headers={ContentType=new("application/json")}};HttpResponseMessage response;try{response=await _http.SendAsync(request,HttpCompletionOption.ResponseHeadersRead,cancellationToken);}catch(OperationCanceledException)when(!cancellationToken.IsCancellationRequested){throw new MerchantApiException(0,"timeout","request timed out",retryable:true);}catch(HttpRequestException){throw new MerchantApiException(0,"transport_error","request failed",retryable:true);}await using var stream=await response.Content.ReadAsStreamAsync(cancellationToken);JsonDocument document;try{document=await JsonDocument.ParseAsync(stream,cancellationToken:cancellationToken);}catch(JsonException){throw new MerchantApiException((int)response.StatusCode,"invalid_response","server returned invalid JSON",response.Headers.TryGetValues("Request-Id",out var ids)?ids.FirstOrDefault():null);}var root=document.RootElement.Clone();document.Dispose();if(!response.IsSuccessStatusCode){var error=root.TryGetProperty("error",out var node)?node:default;var code=error.ValueKind==JsonValueKind.Object&&error.TryGetProperty("code",out var c)?c.GetString()??"http_error":"http_error";var message=error.ValueKind==JsonValueKind.Object&&error.TryGetProperty("message",out var m)?m.GetString()??"API request failed":"API request failed";throw new MerchantApiException((int)response.StatusCode,code,message,root.TryGetProperty("request_id",out var rid)?rid.GetString():null,null,response.StatusCode==HttpStatusCode.TooManyRequests||(int)response.StatusCode>=500,ParseRetryAfter(response));}return root;}
    private static TimeSpan? ParseRetryAfter(HttpResponseMessage response){if(!response.Headers.TryGetValues("Retry-After",out var values)||!int.TryParse(values.FirstOrDefault(),out var seconds))return null;return TimeSpan.FromSeconds(Math.Clamp(seconds,0,300));}
    private Task<Envelope<T>> EnvelopeAsync<T>(JsonElement root){var value=root.GetProperty("data").Deserialize<T>(_json)??throw new MerchantApiException(200,"invalid_response","invalid API response");return Task.FromResult(new Envelope<T>(value,root.GetProperty("request_id").GetString()!,root.GetProperty("api_version").GetString()!));}
    private Task<Envelope<JsonElement>> NodeEnvelopeAsync(JsonElement root)=>Task.FromResult(new Envelope<JsonElement>(root.GetProperty("data").Clone(),root.GetProperty("request_id").GetString()!,root.GetProperty("api_version").GetString()!));
    private static IReadOnlyDictionary<string,IReadOnlyList<object?>> Query(params (string Key,object? Value)[] values)=>values.Where(item=>item.Value is not null).ToDictionary(item=>item.Key,item=>(IReadOnlyList<object?>)new object?[]{item.Value});
    internal static void ValidateBaseUrl(string value){if(!Uri.TryCreate(value,UriKind.Absolute,out var uri))throw new ArgumentException("base URL must be an HTTPS origin");var loopback=uri.Scheme=="http"&&(uri.Host=="localhost"||uri.Host=="127.0.0.1");if((uri.Scheme!="https"&&!loopback)||!string.IsNullOrEmpty(uri.UserInfo)||!string.IsNullOrEmpty(uri.Query)||!string.IsNullOrEmpty(uri.Fragment)||(uri.AbsolutePath!="/"&&uri.AbsolutePath!=""))throw new ArgumentException("base URL must be an HTTPS origin");}
}

public sealed class CheckoutClient {
    private readonly string _baseUrl;private readonly HttpClient _http;private readonly JsonSerializerOptions _json=new(){PropertyNamingPolicy=JsonNamingPolicy.SnakeCaseLower,PropertyNameCaseInsensitive=true};
    public CheckoutClient(string baseUrl,TimeSpan? timeout=null){MerchantClient.ValidateBaseUrl(baseUrl);_baseUrl=baseUrl.TrimEnd('/');_http=new HttpClient(new HttpClientHandler{AllowAutoRedirect=false}){Timeout=timeout??TimeSpan.FromSeconds(10)};}
    public async Task<CheckoutSession> GetSessionAsync(string token,CancellationToken cancellationToken=default){if(token is null||!System.Text.RegularExpressions.Regex.IsMatch(token,"^cs_[A-Za-z0-9_-]{43}$"))throw new ArgumentException("invalid checkout token");HttpResponseMessage response;try{response=await _http.GetAsync(_baseUrl+"/v1/checkout-sessions/"+Signing.PathSegment(token),cancellationToken);}catch(HttpRequestException){throw new MerchantApiException(0,"transport_error","checkout request failed",retryable:true);}if(response.StatusCode!=HttpStatusCode.OK)throw new MerchantApiException((int)response.StatusCode,"checkout_unavailable","checkout session unavailable",retryable:response.StatusCode==HttpStatusCode.TooManyRequests||(int)response.StatusCode>=500);var value=await response.Content.ReadFromJsonAsync<CheckoutSession>(_json,cancellationToken)??throw new MerchantApiException(200,"invalid_response","invalid checkout response");var statuses=new[]{"pending","detected","confirming","settled","expired","preparing_payment_route","payment_route_failed"};var waiting=value.Status is "preparing_payment_route" or "payment_route_failed";bool InvalidRoute(CheckoutRoute route){var onChain=route.Provider=="on_chain"&&!string.IsNullOrEmpty(route.Network)&&!string.IsNullOrEmpty(route.Address)&&route.ProviderId is null&&route.PaymentUrl is null;var hosted=route.Provider=="hosted_gateway"&&!string.IsNullOrEmpty(route.ProviderId)&&route.PaymentUrl?.StartsWith("https://",StringComparison.Ordinal)==true&&route.Network is null&&route.Address is null&&route.TransactionHash is null&&route.ExplorerUrl is null;return string.IsNullOrEmpty(route.Id)||string.IsNullOrEmpty(route.Asset)||!System.Text.RegularExpressions.Regex.IsMatch(route.Amount,"^\\d+(\\.\\d+)?$")||(!onChain&&!hosted);}if(!statuses.Contains(value.Status)||value.Routes is null||(waiting?(value.Routes.Count!=0||value.SelectedRouteId!=""):value.Routes.Count==0)||value.Routes.Any(InvalidRoute)||(value.SelectedRouteId.Length>0&&!value.Routes.Any(route=>route.Id==value.SelectedRouteId)))throw new MerchantApiException(200,"invalid_response","invalid checkout response");return value;}
    public async Task<JsonElement> GetPaymentLinkAsync(string token,CancellationToken cancellationToken=default)=>await PublicAsync(HttpMethod.Get,"/v1/public/payment-links/"+Signing.PathSegment(Capability(token,"pl")),null,null,null,cancellationToken);
    public async Task<JsonElement> RedeemPaymentLinkAsync(string token,string key,object? value=null,string? origin=null,CancellationToken cancellationToken=default)=>await PublicAsync(HttpMethod.Post,"/v1/public/payment-links/"+Signing.PathSegment(Capability(token,"pl"))+"/redeem",value??new{},key,origin,cancellationToken);
    public async Task<CheckoutSession> SelectRouteAsync(string token,string routeId,string key,string? origin=null,CancellationToken cancellationToken=default){var value=await PublicAsync(HttpMethod.Post,"/v1/checkout-sessions/"+Signing.PathSegment(Capability(token,"cs"))+"/select-route",new{route_id=routeId},key,origin,cancellationToken);return value.Deserialize<CheckoutSession>(_json)??throw new MerchantApiException(200,"invalid_response","invalid checkout response");}
    private async Task<JsonElement> PublicAsync(HttpMethod method,string path,object? value,string? key,string? origin,CancellationToken token){var body=value is null?null:JsonSerializer.SerializeToUtf8Bytes(value,_json);using var request=new HttpRequestMessage(method,_baseUrl+path);request.Headers.Accept.ParseAdd("application/json");if(key is not null)request.Headers.TryAddWithoutValidation("Idempotency-Key",key);if(origin is not null)request.Headers.TryAddWithoutValidation("Origin",origin);if(body is not null)request.Content=new ByteArrayContent(body){Headers={ContentType=new("application/json")}};using var response=await _http.SendAsync(request,token);if(!response.IsSuccessStatusCode)throw new MerchantApiException((int)response.StatusCode,"checkout_unavailable","public checkout request failed",retryable:response.StatusCode==HttpStatusCode.TooManyRequests||(int)response.StatusCode>=500);return JsonDocument.Parse(await response.Content.ReadAsByteArrayAsync(token)).RootElement.Clone();}
    private static string Capability(string value,string prefix){if(value is null||!System.Text.RegularExpressions.Regex.IsMatch(value,"^"+prefix+"_[A-Za-z0-9_-]{43}$"))throw new ArgumentException("invalid capability token");return value;}
}
